#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

echo "TODO: implement"
echo "TODO confirm and delete all files from destination directory"
gcp-storage::copy-from "${@}"

taito::call_next "${@}"
