#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

echo "TODO: implement"

if [[ ${taito_host_uname:-} == "Darwin" ]]; then
  echo "macOS not supported"
  echo
  exit 1
fi

bucket="${taito_target:-$taito_storages}"
mount_path="./mounts/${bucket}"
mkdir -p "${mount_path}"

# Start rsync for mac hosts (not working)
# if [[ ${taito_host_uname:-} == "Darwin" ]]; then
#   sync_path="${mount_path}"
#   mount_path="${mount_path}-mount"
#   mkdir -p "${mount_path}"
#   (
#     taito::executing_start
#     sleep 4
#     echo "Syncing '${sync_path}' '${mount_path}'"
#     rsync -av --delete "${sync_path}" "${mount_path}"
#   ) &
# fi

echo "Mounting bucket '${bucket}'"
echo
taito::print_note_start
echo "NOTE: Press CTRL-C to unmount"
taito::print_note_end
echo

(
  taito::executing_start
  # TODO remove 777 permission flags once files are no longer owned by root
  gcsfuse --dir-mode 777 --file-mode 777 "${@}" "${bucket}" "${mount_path}"
)

taito::call_next "${@}"
