#!/bin/bash -e
: "${taito_command:?}"

# shellcheck source=../lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

# Set default region just in case
export AWS_DEFAULT_REGION="${taito_provider_region:?}"

# Automatic authentication on 'env apply'
if [[ $taito_command == "env-apply" ]] && [[ "${taito_mode:-}" != "ci" ]]; then
  echo
  echo -e "${taito_command_context_prefix:-}${H1s}aws${H1e}"
  echo "Authenticating"
  aws::authenticate
fi

# Authentication for CI
if [[ "${taito_mode:-}" == "ci" ]]; then
  # Ensure that AWS credentials exist
  if [[ ! "${AWS_ACCESS_KEY_ID}" ]]; then
    echo
    echo -e "${taito_command_context_prefix:-}${H1s}aws${H1e}"
    echo
    echo "ERROR: AWS_ACCESS_KEY_ID environment variable not set."
    echo "Configure AWS_ACCESS_KEY_ID in your CI/CD settings."
    exit 1
  fi
  if [[ ! "${AWS_SECRET_ACCESS_KEY}" ]]; then
    echo
    echo -e "${taito_command_context_prefix:-}${H1s}aws${H1e}"
    echo
    echo "ERROR: AWS_SECRET_ACCESS_KEY environment variable not set"
    echo "Configure AWS_SECRET_ACCESS_KEY in your CI/CD settings."
    exit 1
  fi

  # Container registry (ECR) authentication
  if [[ ${taito_commands_only_chain:-} == *"docker/"* ]]; then
    echo
    echo -e "${taito_command_context_prefix:-}${H1s}aws${H1e}"
    echo "Getting credentials for Elastic Container Registry"
    aws::authenticate_on_ecr
  fi

  # Kubernetes (EKS) authentication
  if [[ ${taito_commands_only_chain:-} == *"kubectl/"* ]] || \
     [[ ${taito_commands_only_chain:-} == *"helm/"* ]] || ( \
       [[ ${kubernetes_db_proxy_enabled:-} == "true" ]] && \
       [[ ${taito_requires_database_connection:-} == "true" ]] \
     ); then
    echo
    echo -e "${taito_command_context_prefix:-}${H1s}aws${H1e}"
    echo "Getting credentials for kubernetes"
    aws::authenticate_on_kubernetes
  fi
fi

taito::call_next "${@}"
