#!/bin/bash -e
# shellcheck source=../lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

# Set default region just in case
export AWS_DEFAULT_REGION="${taito_provider_region:?}"

# Authentication
if [[ ${taito_command:?} == "env-apply" ]] && [[ ${taito_mode:-} != "ci" ]]; then
  taito::print_plugin_title
  echo "Authenticating"
  aws::authenticate
fi

# Authentication for CI
if [[ ${taito_mode:-} == "ci" ]] || [[ "${AWS_ACCESS_KEY_ID}" ]]; then
  # Ensure that AWS credentials exist
  if [[ ! "${AWS_ACCESS_KEY_ID}" ]] && [[ ${taito_ci_provider:-} != "aws" ]]; then
    taito::print_plugin_title
    echo
    echo "ERROR: AWS_ACCESS_KEY_ID environment variable not set."
    echo "Configure AWS_ACCESS_KEY_ID in your CI/CD settings."
    exit 1
  fi
  if [[ ! "${AWS_SECRET_ACCESS_KEY}" ]] && [[ ${taito_ci_provider:-} != "aws" ]]; then
    taito::print_plugin_title
    echo
    echo "ERROR: AWS_SECRET_ACCESS_KEY environment variable not set"
    echo "Configure AWS_SECRET_ACCESS_KEY in your CI/CD settings."
    exit 1
  fi

  # Temporary credentials for database proxy access during testing
  if [[ ${taito_command:-} == "test" ]] && [[ ! "${AWS_ACCESS_KEY_ID}" ]]; then
    echo TODO aws sts get-session-token
  fi

  # Container registry (ECR) authentication
  if [[ ${taito_command_requires_container_registry:?} == "true" ]] &&
     [[ ${taito_container_registry_provider:-} == "aws" ]]
  then
    taito::print_plugin_title
    echo "Getting credentials for Elastic Container Registry"
    aws::authenticate_on_ecr
  fi

  # Kubernetes (EKS) authentication
  if [[ ${taito_command_requires_kubernetes:?} == "true" ]]; then
    taito::print_plugin_title
    echo "Getting credentials for Kubernetes"
    aws::authenticate_on_kubernetes
  fi
fi

taito::call_next "${@}"
