#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

if [[ ${1} == "--save-as-taito-secrets" ]]; then
  save_to_disk=true
else
  save_to_disk=false
  echo 'TODO: Fetch secrets only once!'
  echo 'Showing secret values from AWS SSM Parameter Store:'
  echo
fi

taito::export_secrets \
  aws-secrets::get_secret_value \
  "${save_to_disk}"
taito::print_secret_values "${save_to_disk}"

taito::call_next "${@}"
