#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

args=("${@}")

if [[ ${taito_provider_secrets_location:-} ]] &&
   [[ ${taito_provider_secrets_mode:-} != "backup" ]]; then
  secret_filter=
  save_to_disk=false
  show_files=false

  while [[ $# -gt 0 ]]; do
    key="$1"
    case ${key} in
    --save-as-taito-secrets)
      save_to_disk=true
      shift
      ;;
    --show-files)
      show_files=true
      shift
      ;;
    *)
      secret_filter="${key}"
      show_files=true
      shift
      ;;
    esac
  done

  if [[ ${taito_quiet:-} != "true" ]] &&
     [[ ${save_to_disk} == "false" ]] &&
     [[ ! ${secret_filter} ]]; then
    echo 'TODO: Retrieve secrets only once!'
    echo 'Showing secret values from AWS SSM Parameter Store:'
    echo
  fi

  taito::export_secrets \
    aws-secrets::get_secret_value \
    ${save_to_disk} "${secret_filter}"
  taito::print_secret_values ${save_to_disk} ${show_files} "${secret_filter}"
fi

taito::call_next "${args[@]}"
