#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

echo "Exporting secrets to ${taito_tmp_secrets_dir:?}"
while [[ $# -gt 0 ]]; do
  secret_filter="$1"
  taito::export_secrets aws-secrets::get_secret_value true "${secret_filter}"
  shift
done

taito::call_next "${@}"
