#!/bin/bash -e
# shellcheck source=../lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

# Stop database proxy
if [[ ${gcp_db_proxy_enabled:-} != "false" ]] && \
   [[ ${taito_command_requires_database:-} == "true" ]]; then
  taito::print_plugin_title
  echo "Stopping all db proxies"
  gcp::db_proxy_stop
fi

taito::call_next "${@}"
