#!/bin/bash -e
# shellcheck source=../lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

[[ $gcp_auth_already_done != "true" ]] || taito::skip_to_next "${@}"

# Authentication
if [[ ${taito_command:?} == "env-apply" ]] && [[ ${taito_mode:-} != "ci" ]]; then
  taito::print_plugin_title
  echo "Authenticating"
  gcloud config set disable_usage_reporting True
  gcp::authenticate
fi

# Authenticate automatically if $GOOGLE_APPLICATION_CREDENTIALS has been set
# But skip when there is no environment
if [[ $GOOGLE_APPLICATION_CREDENTIALS ]] &&
    ! ([[ ${taito_mode:-} == "ci" ]] && [[ ${taito_ci_no_env:-} == "true" ]]); then
  if [[ ${taito_verbose:-} == true ]]; then
    echo "GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS"
  fi

  gcloud config set disable_usage_reporting True
  account=$(gcloud config get-value account 2> /dev/null)

  if [[ ${taito_verbose:-} == true ]]; then
    echo "gcloud account: $account"
  fi

  # Ignore *.svc.id.goog because it causes trouble with running GitHub Actions
  # runner on GKE.
  # TODO: remove *.svc.id.goog ignore
  if [[ ! $account ]] || [[ $account == *".svc.id.goog" ]]; then
    taito::print_plugin_title
    echo "Authenticating with key $GOOGLE_APPLICATION_CREDENTIALS"
    if [[ ${taito_verbose:-} == true ]]; then
      echo "GOOGLE_APPLICATION_CREDENTIALS contents:"
      cat "$GOOGLE_APPLICATION_CREDENTIALS"
    fi
    gcloud auth activate-service-account \
      "--key-file=$GOOGLE_APPLICATION_CREDENTIALS" # --project=...
    echo "Authenticated"
    if [[ ${gcp_kubernetes_enabled:-} != "false" ]]; then
      # Force kube login on test proxy port forwarding
      force_kube_login_hack="true"
    fi

    if [[ ${taito_container_registry} == *".pkg.dev"* ]]; then
      echo "Configure docker for GCP: ${taito_container_registry%%/*}"
      gcloud auth configure-docker "${taito_container_registry%%/*}"
    fi
  fi
fi

# Authenticate on Kubernetes
if [[ $force_kube_login_hack == "true" ]] || ( \
     # We skip gcloud auth when GOOGLE_SQL_PROXY_CREDENTIALS is set
     # to mitigate gcloud IPv6 connection problems
     [[ ! "${GOOGLE_SQL_PROXY_CREDENTIALS}" ]] && \
     # Skip auth when there is no environment
     ! ([[ ${taito_mode:-} == "ci" ]] && [[ ${taito_ci_no_env:-} == "true" ]]) && \

     [[ ${gcp_kubernetes_enabled:-} != "false" ]] && \
     [[ ${taito_mode:-} == "ci" ]] && \
     [[ ${kubernetes_name:-} ]] && \
     [[ ! -d "${HOME}/.kube" ]] && \
     [[ ! -d "/root/.kube" ]] \
   ); then
  account=$(gcloud config get-value account 2> /dev/null)
  if [[ $account ]]; then
    taito::print_plugin_title
    echo "Getting GCP credentials for Kubernetes access"
    gcp::authenticate_on_kubernetes
  fi
fi

export gcp_auth_already_done=true

taito::call_next "${@}"
