#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

# Command parameters
duration_hours="${1:?duration not given}"
weekday="${2:-today}"

# with weekdays we always mean 'last mon', 'last tue'
if [[ ${#weekday} -lt 4 ]]; then
  weekday="last ${weekday}"
fi

(
  set -e

  # API token
  toggl::expose_api_token

  # hour entry: project id
  taito::select_item "Projects:" "Enter project name:" \
    "${toggl_projects}" "${toggl_project_id}" true
  project_id="${item_id}"
  if [[ ! ${project_id} ]]; then
    echo "No project selected. Skipping Toggl."
    exit 0
  fi

  # hour entry: task id
  taito::select_item "Tasks:" \
    "Choose task:" "${toggl_tasks}" "${toggl_task_id}"
  task_id="${item_id:-null}"

  # hour entry: time and description
  duration=$(awk "BEGIN { print ${duration_hours/,/.}*3600 }")
  start="$(date -d ${weekday} --iso-8601)T05:00:00.000Z"
  description="${taito_hours_description:?}"

  # Call Toggl API
  taito::executing_start
  output=$(curl -s -u "${toggl_api_token}:api_token" \
  	-H "Content-Type: application/json" \
  	-d "{\"time_entry\":{\"description\":\"${description}\",\"duration\":${duration},\"start\":\"${start}\",\"pid\":${project_id},\"tid\":${task_id},\"created_with\":\"taito-cli\"}}" \
  	https://www.toggl.com/api/v8/time_entries)
  if [[ ${output} == *"${description}"* ]]; then
    echo "Hour entry was saved to Toggl"
  else
    echo "ERROR:"
    echo "${output}"
    exit 1
  fi
)


taito::call_next "${@}"
