#!/bin/bash -e
: "${taito_plugin_path:?}"

hours_app=${1}

if taito::confirm_execution "toggl" "${hours_app}" \
  "Authenticate to Toggl"
then
  "${taito_plugin_path}/util/auth"
fi

taito::call_next "${@}"
