# TODO: Move to a separate repository and then publish to GitHub Marketplace?
name: "Taito CLI"
description: "Run Taito CLI commands on GitHub Actions"
inputs:
  args:
    description: "Taito CLI arguments to run"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.args }}
