# Provides GitHub Actions support for running Taito CLI commands on GA.
name: "Taito CLI"
description: "Run Taito CLI commands on GitHub Actions"
inputs:
  args:
    description: "Taito CLI arguments to run"
    required: true
runs:
  using: "docker"
  image: "docker://ghcr.io/taitounited/taito-cli:ci"
  args:
    - ${{ inputs.args }}
