images: [
  'eu.gcr.io/$PROJECT_ID/$REPO_NAME/cli:$_IMAGE_TAG'
]

substitutions:
  _DOCKERFILE: Dockerfile
  _IMAGE_TAG:

steps:
- id: install
  name: 'gcr.io/cloud-builders/npm:current'
  args: ['install']
- id: secrets
  waitFor: ['-']
  name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "# Get credentials"
    gcloud container clusters get-credentials "kube1" \
      --zone "europe-west1-c"

    # Get github token from Kubernetes secrets
    kubectl --namespace "devops" get secret "github-buildbot" -o yaml | \
      grep "^  token" | sed -e "s/^.*: //" | base64 --decode > github-token.tmp

- id: release-pre
  waitFor: ['secrets']
  name: 'gcr.io/cloud-builders/npm:current'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    github_token=$$(cat github-token.tmp)

    # TODO is git clone / npm install even necessary with the latest
    # semantic release?

    echo "# Cloning git repo to release directory as google container"
    echo "# builder workspace does not point to the original repository"
    git clone "https://${github_token}@github.com/TaitoUnited/taito-cli.git" \
      release
    cd release
    git checkout master
    npm install

    echo "# Running semantic-release pre"
    NPM_TOKEN=none GH_TOKEN=${github_token} npm run release-pre:prod \
      > ./release-output
    cat ./release-output

    # Parse version from semantic-release output
    cat ./release-output | \
      grep "next release version" | \
      grep -o '[0-9]*\.[0-9]*\.[0-9]*' > ../taitoflag_version

- id: build
  name: 'gcr.io/cloud-builders/docker'
  env:
    - project_id=$PROJECT_ID
    - repo_name=$REPO_NAME
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker build -t eu.gcr.io/$${project_id}/$${repo_name}/cli:${_IMAGE_TAG} \
      -f docker/${_DOCKERFILE} .

- id: test
  name: 'gcr.io/cloud-builders/npm:current'
  args: ['run', 'test']

- id: release-post
  name: 'gcr.io/cloud-builders/npm:current'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "# Running semantic-release post"
    github_token=$$(cat github-token.tmp)
    cd release
    NPM_TOKEN=none GH_TOKEN=${github_token} npm run release-post:prod

- id: push
  name: 'gcr.io/cloud-builders/docker'
  env:
    - project_id=$PROJECT_ID
    - repo_name=$REPO_NAME
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # Read version number that semantic-release wrote on the package.json
    # and tag image with it
    tag=$$(cat "./taitoflag_version")
    echo "Using tag $${tag}"
    docker image tag eu.gcr.io/$${project_id}/$${repo_name}/cli:${_IMAGE_TAG} \
      eu.gcr.io/$${project_id}/$${repo_name}/cli:${_IMAGE_TAG}-$${tag}
    echo "Pushing latest"
    docker push eu.gcr.io/$${project_id}/$${repo_name}/cli:${_IMAGE_TAG}
    echo "Pushing $${tag}"
    docker push eu.gcr.io/$${project_id}/$${repo_name}/cli:${_IMAGE_TAG}-$${tag}

# TODO: remove once all image references have been updated
- id: alt-push
  name: 'gcr.io/cloud-builders/docker'
  env:
    - project_id=$PROJECT_ID
    - repo_name=$REPO_NAME
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    alt_reponame=$${repo_name}
    alt_reponame=${alt_reponame/_taitounited_/-taitounited-}
    docker image tag eu.gcr.io/$${project_id}/$${repo_name}/cli:${_IMAGE_TAG} \
       eu.gcr.io/$${project_id}/${alt_reponame}/cli:${_IMAGE_TAG}
    docker push eu.gcr.io/$${project_id}/${alt_reponame}/cli:${_IMAGE_TAG}
