#!/usr/bin/env bash -e

# NOTE: deprecated (moved to bin/taito)
# TODO: remove this file once everyone has reinstalled taito

taito_cli_path=$(
  # Resolve taito-cli path by following symlinks
  source="${BASH_SOURCE[0]}"
  while [[ -h "${source}" ]]; do # resolve until the file is no longer a symlink
    dir="$( cd -P "$( dirname "${source}" )" && pwd )"
    source=$(readlink "${source}")
    [[ "${source}" != /* ]] && source="${taito_cli_path}/${source}"
  done
  dirname "${source}"
)
"${taito_cli_path}/bin/taito" "${@}"
