#!/bin/bash -e

_taito_commands()
{
  pattern=""
  if [[ ${taito_prefix} ]]; then
    pattern="${taito_prefix} "
  fi
  colon_split=""
  if [[ "${taito_full}" == *":"* ]]; then
    colon_split=$(echo "${taito_full}" | sed 's/:[^:]*/:[^:]*/g')
  fi
  opts=$(echo " ${taito_prefix}" | sed "s/ [a-zA-Z].*//")
  taito -q autocomplete "${taito_prefix}" | \
    sed "s/^/${opts} /" | \
    grep -e "${pattern}" | awk "{print \$${taito_index}}" | \
    sed "s/\([^:]*${colon_split}:\).*/\1/"
}

_taito ()
{
  local cur=${COMP_WORDS[COMP_CWORD]}
  export taito_index="${COMP_CWORD}"
  export taito_prefix="${COMP_WORDS[@]:1:$COMP_CWORD-1}"
  export taito_full="${COMP_WORDS[@]:1:$COMP_CWORD}"

  if [[ ${taito_prefix} == *"db import:"* ]] || \
     [[ ${taito_prefix} == *"db dump:"* ]] || \
     [[ ${taito_prefix} == *"db restore:"* ]]; then
    # Autocomplete using filenames
    COMPREPLY=( $( compgen -f -- "${cur}" ) )
  else
    # Autocomplete using taito-cli commands
    COMPREPLY=( $( compgen -W "$(_taito_commands)" -- "${cur}" ) )
  fi

  return 0
}

# TODO how to avoid global COMP_WORDBREAKS change?
export COMP_WORDBREAKS=${COMP_WORDBREAKS//:/}
complete -F _taito taito
