#!/bin/bash

if [[ ${taito_commands_only_chain:-} == *"-db/"* ]]; then
  echo
  echo -e "${taito_command_context_prefix:-}${H1s}azure${H1e}"
  echo "Stopping all db proxies"
  echo "TODO implement"
fi

taito::call_next "${@}"
