#!/bin/bash -e
# shellcheck source=../lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

# Authentication
if [[ ${taito_command:?} == "env-apply" ]] && [[ ${taito_mode:-} != "ci" ]]; then
  taito::print_plugin_title
  echo "Authenticating"
  azure::authenticate
fi

# Authentication for CI
if ( [[ ${taito_mode:-} == "ci" ]] || [[ "${AZURE_CLIENT_ID}" ]] ) && \
    # Do not execute on util-test or secret-export as user may have been switched
    [[ ${taito_command} != "util-test" ]] && \
    [[ ${taito_command} != "secret-export" ]]; then

  # Ensure that AZURE credentials exist
  if [[ ! "${AZURE_CLIENT_ID}" ]]; then
    taito::print_plugin_title
    echo
    echo "ERROR: Configure AZURE_CLIENT_ID environment variable on your CI/CD settings."
    exit 1
  fi
  if [[ ! "${AZURE_CLIENT_SECRET}" ]] && [[ ! "${taito_auth_id_token}" ]]; then
    taito::print_plugin_title
    echo
    echo "ERROR: Configure either AZURE_CLIENT_SECRET environment variable or OIDC token"
    echo "federation on your CI/CD settings."
    exit 1
  fi

  # TODO: What are these used for? Are they obsolete?
  export AAD_SERVICE_PRINCIPAL_CLIENT_ID="${AZURE_CLIENT_ID}"
  export AAD_SERVICE_PRINCIPAL_CLIENT_SECRET="${AZURE_CLIENT_SECRET}"

  if ! az account show &> /dev/null; then

    azure_auth_opts="-u ${AZURE_CLIENT_ID}"
    if [[ "${taito_auth_id_token}" ]]; then
      azure_auth_opts="${azure_auth_opts} --federated-token ${taito_auth_id_token}"
    else if [[ "${AZURE_CLIENT_SECRET}" ]]; then
      azure_auth_opts="${azure_auth_opts} -p ${AZURE_CLIENT_SECRET}"
    fi

    az login ${azure_auth_opts} \
      --tenant "${taito_provider_tenant:-$taito_provider_org_id}" \
      --service-principal
    az account set --subscription "${taito_provider_billing_account_id}"

    # Container registry (ACR) authentication
    if [[ ${taito_command_requires_container_registry:?} == "true" ]] &&
       [[ ${taito_container_registry_provider:-} == "azure" ]]
    then
      taito::print_plugin_title
      echo "Getting credentials for Azure Container Registry"
      azure::authenticate_on_acr
    fi

    # Kubernetes (EKS) authentication
    if [[ ${taito_command_requires_kubernetes:?} == "true" ]]; then
      taito::print_plugin_title
      echo "Getting credentials for Kubernetes"
      azure::authenticate_on_kubernetes
    fi
  fi
fi

taito::call_next "${@}"
