#!/bin/bash -e
# shellcheck source=../lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

# Authentication
if [[ ${taito_command:?} == "env-apply" ]] && [[ ${taito_mode:-} != "ci" ]]; then
  taito::print_plugin_title
  echo "Authenticating"
  azure::authenticate
fi

# Authentication for CI
if [[ ${taito_mode:-} == "ci" ]] || [[ "${AZURE_CLIENT_ID}" ]]; then
  # Ensure that AWS credentials exist
  if [[ ! "${AZURE_CLIENT_ID}" ]] || [[ ! "${AZURE_CLIENT_SECRET}" ]]; then
    taito::print_plugin_title
    echo
    echo "ERROR: AZURE_CLIENT_ID and AZURE_CLIENT_SECRET environment variables not set."
    echo "Configure them in your CI/CD settings."
    exit 1
  fi

  export AAD_SERVICE_PRINCIPAL_CLIENT_ID="${AZURE_CLIENT_ID}"
  export AAD_SERVICE_PRINCIPAL_CLIENT_SECRET="${AZURE_CLIENT_SECRET}"

  if ! az account show &> /dev/null; then
    az login --service-principal -u "${AZURE_CLIENT_ID}" -p "${AZURE_CLIENT_SECRET}" --tenant "${taito_provider_tenant:-$taito_provider_org_id}"
    az account set --subscription "${taito_provider_billing_account_id}"

    # Container registry (ACR) authentication
    if [[ ${taito_command_requires_container_registry:?} == "true" ]] &&
       [[ ${taito_container_registry_provider:-} == "azure" ]]
    then
      taito::print_plugin_title
      echo "Getting credentials for Azure Container Registry"
      azure::authenticate_on_acr
    fi

    # Kubernetes (EKS) authentication
    if [[ ${taito_command_requires_kubernetes:?} == "true" ]]; then
      taito::print_plugin_title
      echo "Getting credentials for Kubernetes"
      azure::authenticate_on_kubernetes
    fi
  fi
fi

taito::call_next "${@}"
