#!/bin/bash -e

image_tag=${1:?}

echo "Checking if image already exists in the container registry"
echo "TODO check from container registry instead as there might be manual \
builds also"

check=$(
  gcloud -q --project "${taito_zone:?}" builds list \
  --filter="status:SUCCESS AND \
            source.repoSource.repoName~.*${taito_vc_repository:?} AND \
            sourceProvenance.resolvedRepoSource.commitSha:${image_tag}"
)

export taito_images_exist
if [[ ! ${check} ]]; then
  echo "Image does not exist"
  taito_images_exist=false
else
  echo "Image exists"
  taito_images_exist=true
  echo "exist" > ./taitoflag_images_exist
fi

taito::call_next "${@}"
