#!/bin/bash -e
: "${taito_zone:?}"
: "${taito_vc_repository:?}"
: "${taito_branch:?}"

ignore_build_id=${1}

echo "Canceling all previous ongoing builds targetting branch ${taito_branch}"
echo

(
  taito::executing_start
  gcloud -q --project "${taito_zone}" builds list \
    --format="table[no-heading](id)" \
    --ongoing \
    --filter=" \
      source.repoSource.repoName~.*${taito_vc_repository} AND ( \
        source.repoSource.branchName:${taito_branch} OR \
        substitutions.BRANCH_NAME:${taito_branch} \
      )" | \
  grep -v "${ignore_build_id:-OR_DO_NOT_IGNORE}" | \
  xargs gcloud --project "${taito_zone}" builds cancel &> /dev/null
  echo CANCELLED
)

taito::call_next "${@}"
