#!/bin/bash -e
: "${taito_zone:?}"
: "${taito_vc_repository:?}"
: "${taito_branch:?}"

if [[ -z $1 ]]; then
  echo "Fetching latest image tag from build history."
  # Detetermine target image automatically
  export taito_target_image
  taito::executing_start
  taito_target_image=$(
    gcloud -q --project "${taito_zone}" builds list \
      --sort-by="~createTime" \
      --format="value(substitutions.COMMIT_SHA)" \
      --filter=" \
        status:SUCCESS AND \
        substitutions._REPO_NAME='${taito_vc_repository}' AND \
        substitutions.BRANCH_NAME='${taito_branch}'" | \
      head -1
  )
  echo "Using tag: ${taito_target_image}"
fi

taito::call_next "${@}"
