#!/bin/bash -e
# shellcheck source=../lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"
: "${taito_command:?}"
: "${run_scripts_location:?}"

# Run post scripts from scripts/run directory
script="${run_scripts_location}/taito-${taito_command}#post"
if [[ -f ${script} ]]; then
  export taito_hook_command_executed=true
  echo
  echo -e "${taito_command_context_prefix:-}${H1s}run${H1e}"
  if taito::confirm "Run script ${script}?" yes yes; then
    taito::execute_with_ssh_agent "${script}" "${@}"
  fi
fi

# Runs a process if run_after_for_XXX setting is set for one of the
# plugins in the current command chain
run::run run_after_for_

# kill started run processes
for run_pid in ${ssh_background_pids:-}
do
  kill "${run_pid}"
done

taito::call_next "${@}"
