#!/bin/bash -e
# shellcheck source=../lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

# Fetch required secrets from local disk
taito::expose_required_secrets_filter
if [[ ${fetch_secrets:?} == "true" ]]; then
  script="${run_scripts_location:?}/taito-prehook-fetch-secrets.sh"
  if [[ -f ${script} ]]; then
    taito::print_plugin_title
    if taito::confirm "Get secrets with script ${script}?" yes yes; then
      echo
      taito::execute_with_ssh_agent "${script}" "${secret_filter}"
    fi
  fi
fi

taito::call_next "${@}"
