#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

if [[ ${taito_provider_secrets_location:-} ]] &&
   [[ ${taito_type:-} != "zone" ]]; then
  taito::confirm "Save newly created secrets to Google Cloud Platform" || \
    taito::skip_to_next "${@}"

  backup_mode=false
  if [[ ${taito_provider_secrets_mode:-} == "backup" ]]; then
    backup_mode=true
  fi

  taito::save_secrets \
    gcp-secrets::get_secret_value \
    gcp-secrets::put_secret_value \
    ${backup_mode}
fi

taito::call_next "${@}"
