#!/bin/bash -e
# shellcheck source=../lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"
: "${taito_command:?}"

if [[ ${taito_command} == "open-"* ]]; then
  link_mode="open"
elif [[ ${taito_command} == "link-"* ]]; then
  link_mode="link"
fi
link_name=${taito_command:5:99}

if [[ ! -z ${link_mode} ]]; then
  if links-global::open_link "${link_name}" "${link_mode}"; then
    export taito_hook_command_executed="true"
  fi
fi

taito::call_next "${@}"
