#!/bin/bash
: "${taito_plugin_path:?}"
: "${taito_env:?}"
: "${database_name:?}"

port="${1}"

(
  if [[ "${port}" ]]; then
    export database_port="${port}"
  fi

  echo "Database connection details:"
  taito::show_db_proxy_details
  echo
  "${taito_plugin_path}/util/db-proxy-start" && \
  "${taito_plugin_path}/util/db-proxy-stop"
) && \

taito::call_next "${@}"
