#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"
: "${taito_env:?}"
: "${database_name:?}"

port="${1}"

if [[ "${port}" ]]; then
  database_port="${port}"
fi

echo "Database connection details:"
taito::show_db_proxy_details
echo
gcp::db_proxy_start false
gcp::db_proxy_stop

taito::call_next "${@}"
