#!/bin/bash -e

if [[ "${ssh_db_proxy:-}" ]]; then
  . ${taito_plugin_path}/util/opts
  forward_value=$(echo "$ssh_db_proxy" | taito::substitute_variable_values_in_file)
  (
    ${taito_setv:?}
    sh -c "ssh ${opts} -4 -f -o ExitOnForwardFailure=yes ${forward_value} sleep 180"
  )

  echo
  echo "Database connection details:"
  taito::show_db_proxy_details
  echo
  echo
  echo "Press enter to shutdown proxy"
  read -r
fi

taito::call_next "${@}"
