#!/bin/bash -e

if [[ ${ssh_db_proxy:-} ]]; then
  taito::expose_ssh_opts
  forward_value=$(echo "$ssh_db_proxy" | envsubst)
  (
    taito::executing_start
    sh -c "ssh ${ssh_opts} -4 -f -o ExitOnForwardFailure=yes ${forward_value} sleep 2000"
  )

  echo
  echo "Database connection details:"
  taito::show_db_proxy_details
  echo
  echo
  echo "Press enter to shutdown proxy"
  read -r
fi

taito::call_next "${@}"
