#!/bin/bash -e
: "${taito_host_uname:?}"

if [[ ! ${taito_target:-} ]]; then
  taito::expose_ssh_opts
  (
    ${taito_setv:?}
    ssh -t ${ssh_opts} "${taito_ssh_user:?}@${taito_host}" \
      "cd ${taito_host_dir:?}; bash"
  )
fi

taito::call_next "${@}"
