#!/bin/bash -e

if [[ ! ${taito_target:-} ]]; then
  taito::expose_ssh_opts
  (
    taito::executing_start
    ssh -t ${ssh_opts} "${taito_host:?}" \
      "cd ${taito_host_dir:?}; bash"
  )
fi

taito::call_next "${@}"
