#!/bin/bash
: "${taito_host_uname:?}"

if [[ ! ${taito_target:-} ]]; then
  . ${taito_plugin_path}/util/opts
  (
    ${taito_setv:?}
    ssh -t ${opts} "${taito_ssh_user:?}@${taito_host}" \
      "cd ${taito_host_dir:?}; bash"
  )
fi

taito::call_next "${@}"
