#!/bin/bash -e
: "${taito_plugin_path:?}"
: "${taito_env:?}"
: "${database_name:?}"

(
  all=$(taito::print_targets_of_type database)
  databases=("${taito_target:-$all}")
  for database in ${databases[@]}
  do
    export taito_target="${database}"
    . "${taito_util_path}/read_database_config.bash" "${database}"

    echo "Deploying changes to database ${taito_env}"
    "${taito_plugin_path}/util/deploy-changes" "${@}"
  done
)

taito::call_next "${@}"
