#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

options=" ${*} "

(
  databases=("${taito_target:-$taito_databases}")
  for database in ${databases[@]}; do
    export taito_target="${database}"
    taito::export_database_config "${database}"

    if [[ ${options} == *" --clean "* ]]; then
      echo "Rebasing database ${database_name:?}"
      (sqitch::run rebase --set env="'${taito_env}'") || sqitch::deploy
    else
      echo "Deploying changes to database ${taito_env}"
      (sqitch::deploy) || :
    fi
  done
)

taito::call_next "${@}"
