#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

switches=" ${*} "

(
  all=$(taito::print_targets_of_type database)
  databases=("${taito_target:-$all}")
  for database in ${databases[@]}
  do
    export taito_target="${database}"
    taito::export_database_config "${database}"

    if [[ "${switches}" == *"--clean"* ]]; then
      echo "Rebasing database ${database_name:?}"
      sqitch::run rebase --set env="'${taito_env}'" || "${taito_plugin_path}/util/deploy-changes"
    else
      echo "Deploying changes to database ${taito_env}"
      sqitch::deploy
    fi
  done
)

taito::call_next "${@}"
