#!/bin/bash -e
: "${taito_plugin_path:?}"
: "${taito_env:?}"

switches=" ${*} "

(
  all=$(taito::print_targets_of_type database)
  databases=("${taito_target:-$all}")
  for database in ${databases[@]}
  do
    export taito_target="${database}"
    . "${taito_util_path}/read_database_config.bash" "${database}"

    if [[ "${switches}" == *"--clean"* ]]; then
      echo "Rebasing database ${database_name:?}"
      "${taito_plugin_path}/util/sqitch" rebase --set env="'${taito_env}'" || "${taito_plugin_path}/util/deploy-changes"
    else
      echo "Deploying changes to database ${taito_env}"
      "${taito_plugin_path}/util/deploy-changes"
    fi
  done
)

taito::call_next "${@}"
