#!/bin/bash -e
# shellcheck source=../do/lib/all.bash
. "${taito_cli_path:?}/plugins/do/lib/all.bash"

( [[ ${kubernetes_name:-} ]] && \
    taito::confirm "Authenticate to Kubernetes ${kubernetes_name:-}"
) || taito::skip_to_next "${@}"

echo "Authenticating"
do::authenticate_on_kubernetes
taito::commit_changes

taito::call_next "${@}"
