#!/bin/bash -e

taito::confirm "Create IAM policies?" || taito::skip_to_next "${@}"

echo
echo "1) Create KubernetesCICD policy with actions eks:DescribeCluster and"
echo "   eks:ListClusters enabled"
echo "2) Create KubernetesDeveloper policy with actions eks:DescribeCluster and"
echo "   eks:ListClusters enabled"
echo
echo "See the following link for examples: https://docs.aws.amazon.com/eks/latest/userguide/security_iam_id-based-policy-examples.html"
echo
echo "NOTE: You can skip this step if you have already previously created"
echo "these policies on your AWS account for some other taito zone"
echo
echo "Press enter to open the AWS IAM console for creating the policies"
read -r
taito::open_browser "https://console.aws.amazon.com/iam/home?#policies"

taito::call_next "${@}"
