#!/bin/bash -e

( [[ ${kubernetes_name} ]] && \
    taito::confirm "Configure CI/CD user/role access to Kubernetes cluster"
) || taito::skip_to_next "${@}"

echo
echo "The CI/CD user/role needs to have deployment rights for the Kubernetes cluster."
echo "You can add the rights in your taito zone configuration files like this,"
echo "if you have not done so already:"
echo
if [[ ${taito_ci_provider:?} == "aws" ]]; then
  echo "1) Edit 'terraform/variables.tf': add the CI/CD role to 'map_roles'."
else
  echo "1) Edit 'terraform/variables.tf': add the CI/CD user to 'map_users'."
fi
echo "2) Run 'taito zone apply' and execute only the terraform step."
echo
echo "Press enter when done."
read -r

taito::call_next "${@}"
