#!/bin/bash -e
: "${taito_plugin_path:?}"

name=${1}

if [[ -n "${kubernetes_name:-}" ]]; then
  if taito::confirm_execution "aws-auth" "${name}" \
    "Authenticate to Kubernetes ${kubernetes_name:-}"
  then
    echo "Authenticating"
    "${taito_cli_path}/plugins/aws/util/get-credentials-kube"
    taito::commit_changes
  fi
fi

taito::call_next "${@}"
