#!/bin/bash -e
# shellcheck source=../kubectl/lib/context.bash
. "${taito_plugin_path:?}/../kubectl/lib/context.bash"

if [[ ${taito_default_domain:-} ]]; then
  echo "If you want to manage your ${taito_default_domain} DNS settings in AWS,"
  echo "you may need to add NS records for the main domain. You can check"
  echo "${taito_default_domain} hosted zone NS records from AWS console."
  echo
  echo "Press enter to open hosted zones on AWS console"
  read -r
  taito::open_browser \
    "https://console.aws.amazon.com/route53/home?region=${taito_provider_region:?}#hosted-zones:"
  echo
  echo "Press enter once you have configured DNS"
  read -r
fi

taito::call_next "${@}"
