#!/bin/bash -e

hours_app=${1}

if taito::confirm_execution "jira" "${hours_app}" \
  "Authenticate to JIRA"
then
  echo "TODO implement. Use jq, python or node for json handling."
fi

taito::call_next "${@}"
