#!/bin/bash -e
# shellcheck source=../lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

if [[ ${kubernetes_db_proxy_enabled:-} == "true" ]] && \
   [[ ${taito_requires_database_connection:-} == "true" ]]; then
  echo
  echo -e "${taito_command_context_prefix:-}${H1s}kubectl${H1e}"
  echo "Stopping all db proxies"
  kubectl::db-proxy-stop
fi

if [[ ${taito_command:-} == "test" ]] && \
   [[ ${taito_mode:-} == "ci" ]] && \
   [[ ${taito_proxy_credentials_local_file:-} ]] && \
   [[ -f $taito_proxy_credentials_local_file ]]; then
  echo
  echo -e "${taito_command_context_prefix:-}${H1s}kubectl${H1e}"
  echo "Deleting proxy credentials from disk"
  rm -f "$taito_proxy_credentials_local_file"
fi

taito::call_next "${@}"
