#!/bin/bash -e
# shellcheck source=../lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

# Stop database proxy
if [[ ${kubernetes_db_proxy_enabled:-} == "true" ]] && \
   [[ ${taito_command_requires_database:-} == "true" ]]; then
  taito::print_plugin_title
  echo "Stopping all db proxies"
  kubectl::db-proxy-stop
fi

# Delete temporary secret files
if [[ ${taito_command:-} == "test" ]] && \
   [[ ${taito_mode:-} == "ci" ]] && \
   [[ ${taito_proxy_credentials_local_file:-} ]] && \
   [[ -f $taito_proxy_credentials_local_file ]]; then
  taito::print_plugin_title
  echo "Deleting proxy credentials from disk"
  rm -f "$taito_proxy_credentials_local_file"
fi

taito::call_next "${@}"
