#!/bin/bash -e
# shellcheck source=../lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

# Authentication
if [[ ${taito_command:?} == "env-apply" ]] && [[ ${taito_mode:-} != "ci" ]]; then
  taito::print_plugin_title
  echo "Authenticating"
  # shellcheck disable=SC2119
  openshift::authenticate
fi

# Authentication for CI
if [[ ${taito_mode:-} == "ci" ]]; then
  taito::print_plugin_title
  echo "Authenticating"
  # shellcheck disable=SC2119
  openshift::authenticate

  # Container registry authentication
  # if [[ ${taito_command_requires_container_registry:?} == "true" ]] &&
  #    [[ ${taito_container_registry_provider:-} == "openshift" ]]
  # then
  #   taito::print_plugin_title
  #   echo "Getting credentials for Container Registry"
  #   openshift::authenticate_on_container_registry
  # fi
fi

taito::call_next "${@}"
