#!/bin/bash -e
: "${taito_plugin_path:?}"
: "${taito_project:?}"

commands=$(printf '"%s" ' "${@}")

# shellcheck disable=SC1090
. "${taito_plugin_path}/util/determine-pod"

if [[ -n "${docker_run:-}" ]]; then
  # Using run mode instead of up
  # TODO take --no-deps as param
  compose_file=$("$taito_plugin_path/util/prepare-compose-file")
  taito::execute_on_host_fg \
    "docker-compose -f $compose_file run --no-deps --entrypoint ${commands} ${pod}"
else
  taito::execute_on_host_fg "docker exec -it ${pod} ${commands}"
fi
