#!/bin/bash -e
: "${taito_util_path:?}"
: "${taito_plugin_path:?}"
: "${taito_namespace:?}"
: "${taito_project:?}"
: "${taito_target_env:?}"

revision="${1:-0}"

"${taito_cli_path}/plugins/kubectl/util/use-context"
(
  ${taito_setv:?}
  "${taito_plugin_path}/util/helm" rollback \
    "${taito_project}-${taito_target_env}" "${revision}"
)

# Call next command on command chain
"${taito_util_path}/call-next" "${@}"
