#!/bin/bash -e
: "${taito_plugin_path:?}"
: "${taito_namespace:?}"

"${taito_cli_path}/plugins/kubectl/util/use-context"
if [[ "${taito_mode:-}" != "ci" ]] || [[ "${ci_exec_deploy:-}" != "false" ]]; then
  "${taito_plugin_path}/util/deploy" "${@}"
fi

taito::call_next "${@}"
