#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"
# shellcheck source=../kubectl/lib/context.bash
. "${taito_plugin_path:?}/../kubectl/lib/context.bash"

kubectl::use_context
if [[ "${taito_mode:-}" != "ci" ]] || \
   [[ "${ci_exec_deploy:-}" != "false" ]]
then
  helm::deploy "${@}"
fi

taito::call_next "${@}"
