#!/bin/bash -e
: "${taito_plugin_path:?}"
: "${taito_namespace:?}"
: "${taito_project:?}"
: "${taito_target_env:?}"

"${taito_cli_path}/plugins/kubectl/util/use-context"
(
  ${taito_setv:?}
  "${taito_plugin_path}/util/helm" history \
    "${taito_project}-${taito_target_env}"
)

taito::call_next "${@}"
