#!/bin/bash -e
: "${taito_util_path:?}"
: "${taito_plugin_path:?}"
: "${taito_namespace:?}"

"${taito_cli_path}/plugins/kubectl/util/use-context"
if [[ "${taito_mode:-}" != "ci" ]] || [[ "${ci_exec_deploy:-}" != "false" ]]; then
  "${taito_plugin_path}/util/deploy" "${@}"
fi

# Call next command on command chain
"${taito_util_path}/call-next" "${@}"
