#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"
# shellcheck source=../kubectl/lib/context.bash
. "${taito_plugin_path:?}/../kubectl/lib/context.bash"

options=" ${*} "
if [[ "${options}" == *" --all "* ]]; then
  kubectl::use_context
  helm::run list --namespace "${taito_namespace}"
else
  echo "See helm releases with '--all'"
fi

taito::call_next "${@}"
