#!/bin/bash -e
: "${taito_util_path:?}"
: "${taito_plugin_path:?}"
: "${taito_namespace:?}"

options=" ${*} "
if [[ "${options}" == *" --all "* ]]; then
  "${taito_cli_path}/plugins/kubectl/util/use-context"
  "${taito_plugin_path}/util/helm" list --namespace "${taito_namespace}"
else
  echo "See helm releases with '--all'"
fi

# Call next command on command chain
"${taito_util_path}/call-next" "${@}"
