#!/bin/bash
: "${taito_plugin_path:?}"
: "${taito_project_path:?}"
: "${taito_command:?}"

switches=" ${*} "

# auth command pre-handling
# if [[ "${taito_command:-}" == "auth" ]]; then
#   echo
#   echo -e "${taito_command_context_prefix:-}${H1s}basic${H1e}"
#   echo "Deleting old credentials (but not committing the change yet!)"
#   rm -rf ~/.config ~/.kube
# fi

if [[ ${taito_command} == "env-apply" ]] && \
   [[ "${switches}" == *"--clean"* ]]; then
  rm -rf "${taito_project_path}/tmp"
  rm -rf "${taito_project_path}/secrets"
fi

# env-destroy command pre-handling
if [[ ${taito_command:-} == "env-destroy" ]] || \
   [[ ${taito_command:-} == "env-alt-destroy" ]]; then
  echo
  echo -e "${taito_command_context_prefix:-}${H1s}basic${H1e}"
  echo "Deleting ${taito_target_env:?} environment of ${taito_project:?}"
  taito::confirm "Do you really want to continue?" no
fi

taito::call_next "${@}"
