#!/bin/bash -e

if [[ ${taito_mode:?} == "ci" ]] && \
   [[ ${taito_command:?} == "build-prepare" ]] && \
   [[ ${HOME:?} != "/root" ]] && \
   [[ ${HOME} != "/home/$(whoami)" ]]; then
  taito::print_plugin_title
  /taito-cli-deps/tools/user-init.sh
fi

if [[ ${taito_command} == "test" ]]; then
  for secret in ${taito_testing_secrets[@]}; do
    (
      export taito_command_context='test'
      taito ${taito_options:-} secret export:$taito_env ${secret%:*}
    )
  done
fi

taito::call_next "${@}"
