#!/bin/bash -e

if [[ ${taito_mode:?} == "ci" ]] && \
   [[ ${taito_command:?} == "build-prepare" ]] && \
   [[ ${HOME:?} != "/root" ]] && \
   [[ ${HOME} != "/home/$(whoami)" ]]; then
  taito::print_plugin_title
  /taito-cli-deps/tools/user-init.sh
fi

if [[ ${taito_command} == "db-deploy" ]] ||
   [[ ${taito_command} == "test" ]]; then
  # NOTE: taito_testing_secrets for backwards compatibility
  cicd_secrets=("${taito_cicd_secrets} ${taito_testing_secrets}")
  for secret in ${cicd_secrets[@]}; do
    (
      export taito_command_context="${taito_command}"
      taito -c ${taito_options:-} secret export:$taito_env ${secret%:*}
    )
  done
fi

taito::call_next "${@}"
