#!/bin/bash -e

taito::confirm "Configure VPN connection for your CI/CD" || \
  taito::skip_to_next "${@}"

echo
echo "If you haven't already, add one of the vpn/*.ovpn files to you CI/CD"
echo "as organizational level secret named OVPN_FILE. Add also secret"
echo "OVPN_PASSWORD that contains the password required to decrypt the private"
echo "key contained in the ovpn file".
echo
echo "NOTE: If you have multiple zones, you may also want to define environment"
echo "specific secret overrides, for example:"
echo "STAG_OVPN_FILE, CANARY_OVPN_FILE, PROD_OVPN_FILE"

if [[ ${taito_vc_provider} == "github" ]]; then
  echo
  echo "Configure the aforementioned secrets as organization level secrets on GitHub."
  echo
fi

echo "Press enter when ready."
read -r

taito::call_next "${@}"
