#!/bin/bash -e

if [[ ${1} == "-c"* ]]; then
  collection="${2}"
  name="${3}"
else
  collection="misc"
  name="${1}"
fi

taito_secrets_key=TODO
taito_secrets_keyring=TODO
taito_secrets_region=TODO
taito_secrets_tzone=TODO
taito_secrets_url=gs://TODO/secrets/${collection}
taito_secrets_backup_url=gs://TODO/old/secrets/${collection}

echo "NOTE: If the secret is project specific, use git repository name as"
echo "a prefix. For example: auron-exlib-example"
echo

if [[ ${name} == "" ]]; then
  echo "Secret name:"
  read -r name
fi

if taito::confirm "Generate a random password?"; then
  # TODO better tool for this?
  password=$(openssl rand -base64 30 | sed -e 's/[^a-zA-Z0-9]/a/g')
  password2=${password}
  echo "Generated password: ${password}"
else
  echo "New password for ${name}:"
  read -r -s password

  echo "New password for ${name} again:"
  read -r -s password2
fi

echo "Validating."
if [[ ${password} != "${password2}" ]]; then
  echo "ERROR: Passwords do not match"
  exit 1
elif [[ ! "${#password}" -ge 10 ]]; then
  (>&2 echo "ERROR: Why so short password? :( I'm not gonna save it!!!!")
  (>&2 echo)
  exit 1
elif [[ ${#password} -ge 20 ]]; then
  echo "OK! Now that's a long password ;)"
else
  echo "OK!"
fi

echo "Encrypting."
# TODO do not use tmp files
mkdir -p "${HOME}/tmp"
cipher_path="${HOME}/tmp/cipher.tmp"
echo "${password}" | gcloud kms encrypt \
  --keyring "${taito_secrets_keyring}" \
  --key "${taito_secrets_key}" \
  --location "${taito_secrets_region}" \
  --plaintext-file '-' \
  --ciphertext-file "${cipher_path}" \
  --project "${taito_secrets_tzone}"
if [[ $? -gt 0 ]]; then
  echo "ERROR: Encrypting password failed."
  rm -f "${cipher_path}"
  exit 1
fi

if gsutil ls "${taito_secrets_url}/${name}" &> /dev/null; then
  # NOTE: This is futile if bucket versioning is enabled
  echo "Making a backup."
  gsutil cp "${taito_secrets_url}/${name}" \
    "${taito_secrets_backup_url}/${name}.$(date +%s)" &> /dev/null
fi

echo "Saving new password."
if ! gsutil cp "${cipher_path}" "${taito_secrets_url}/${name}"; then
  echo "ERROR: Copying encrypted password to bucket failed."
  rm -f "${cipher_path}"
  exit 1
fi

# Clean up
rm -f "${cipher_path}"

taito::call_next "${@}"
