#!/bin/bash -e
: "${taito_host_uname:?}"

taito::confirm "Apply changes by running ansible scripts" || \
  taito::skip_to_next

(
  function cleanup {
    rm -f ansible-playbooks/taito-ansible.cfg &> /dev/null
  }
  trap cleanup EXIT

  ansible_options="${ansible_options:-}"

  echo "Inventories:"
  ls -p ansible-playbooks | grep -v / | grep -v "\."
  echo
  echo "Select inventory:"
  read -r inventory
  if [[ ${inventory} ]]; then
    ansible_options="${ansible_options} -i ${inventory}"
  fi

  echo
  echo "Groups and hosts in ansible inventory:"
  grep "^\\[" "ansible-playbooks/${inventory}" | \
    sed "s/\\[//" | \
    sed "s/\\]//" | \
    tr '\n' ' ' || \
    :
  echo
  grep "^[a-z]" "ansible-playbooks/${inventory}" | sort | uniq
  echo
  echo "Enter limit for ansible (e.g. group or hostname) or leave empty to run"
  echo "all in inventory '${inventory}':"
  read -r limit
  if [[ ${limit} ]]; then
    ansible_options="${ansible_options} --limit ${limit}"
  fi

  if taito::confirm "Log in with password"; then
    ansible_options="$ansible_options --ask-pass"
  fi

  if [[ -f "${HOME}/.ssh/config.taito" ]]; then
    taito::executing_start
    printf "[ssh_connection]\nssh_args = -F${HOME}/.ssh/config.taito\n" \
      > ansible-playbooks/taito-ansible.cfg
    export ANSIBLE_CONFIG="${PWD}/ansible-playbooks/taito-ansible.cfg"
    set +x
  elif [[ ${taito_host_os:-} == "macos" ]]; then
    echo
    echo "WARNING! ~/.ssh/config.taito file does not exist! SSH execution will"
    echo "fail if your ~/.ssh/config file contains any macOS specific properties"
    echo "(e.g. UseKeyChain)."
  fi

  cd ansible-playbooks
  if [[ $ansible_options != *"--ask-pass"* ]]; then
    # running ssh-add before ansible-playbook is required because otherwise
    # ansible parallel execution asks for keyphrase for multiple servers at
    # once and only one of them succeeds
    echo "Enter SSH key name or leave empty to use the default [id_rsa}]:"
    read -r keyname
    keyname=${keyname:-id_rsa}
  fi

  taito::execute_with_ssh_agent "
    taito::executing_start
    if [[ \"${keyname}\" ]]; then
      ssh-add "${HOME}/.ssh/${keyname:-id_rsa}";
    fi
    echo
    echo Executing ansible playbooks...
    ansible-playbook ${ansible_options:-} site.yml
  "
)

taito::call_next "${@}"
