FROM ghcr.io/taitounited/taito-cli-deps:ci-aws
MAINTAINER Taito United <support@taitounited.fi>
LABEL fi.taitounited.taito-cli="true"

USER root

# TODO: move to taito-cli-deps basic install set
RUN apt-get -qqy update && apt-get -qqy install zip

COPY . /taito-cli
WORKDIR /taito-cli
RUN ln -s /taito-cli/src/execute-command /usr/local/bin/taito
# RUN npm run verify

ENTRYPOINT ["taito"]
