# TODO: Back to ci-gcp once gcloud auth works properly on CI/CD test db proxy
# or once all projects have been updated to use GOOGLE_SQL_PROXY_CREDENTIALS.
FROM ghcr.io/taitounited/taito-cli-deps:ci-gcp-gcloud457
LABEL fi.taitounited.taito-cli="true"

USER root

COPY . /taito-cli
WORKDIR /taito-cli
RUN ln -s /taito-cli/src/execute-command /usr/local/bin/taito
# RUN npm run verify

# NOTE: Using root user as docker.sock access is often required on CI/CD
ENV taito_mode ci
ENTRYPOINT ["taito"]

# TODO: remove
USER 1006:1003
