FROM ghcr.io/taitounited/taito-cli-deps:all
MAINTAINER Taito United <support@taitounited.fi>
LABEL fi.taitounited.taito-cli="true"

USER root

COPY . /taito-cli
WORKDIR /taito-cli
RUN ln -s /taito-cli/src/execute-command /usr/local/bin/taito
# RUN npm run verify

RUN sed -i "s|./get_helm.sh \&\&|./get_helm.sh -v v3.3.1 \&\&|" \
  /taito-cli-deps/tools/install-helm.sh
RUN /taito-cli-deps/tools/install-helm.sh
RUN /taito-cli-deps/tools/user-init.sh root

ENTRYPOINT ["taito"]
