#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"
: "${taito_container_registry:?}"

# Containers, functions and static assets are built with Docker
taito::skip_if_not "container function static_content" "${@}"

name=${taito_target:?Target not given}
image_tag=${1:?Image tag not given}
image_path=${2}

path_suffix=""
if [[ ${name} != "." ]]; then
  path_suffix="/${name}"
fi

if [[ ${image_path} == "" ]]; then
  image_path="${taito_container_registry}"
fi

prefix="${image_path}${path_suffix}"
image="${prefix}:${image_tag}"

echo "image: ${image}"

if [[ -f ./taitoflag_images_exist ]]; then
  echo "Skipping artifact release. Image already exists in registry."
elif [[ ${taito_targets:-} != *"${name}"* ]]; then
  echo "ERROR: Artifact ${name} not included in taito_targets."
  exit 1
else
  if [[ -f "${name}.docker" ]]; then
    echo "Load ${name}.docker"
    (taito::executing_start; docker load --input "${name}.docker")
  fi
  echo "Push ${image}"
  docker::image_push "${image}"
fi

taito::call_next "${@}"
