#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"
: "${taito_target:?}"

# Containers, functions and static assets are built with Docker
taito::skip_if_not "container function static_content" "${@}"

export taito_docker_new_params=true
docker::build "${@}"

if (
     taito::is_current_target_of_type container ||
     [[ ${taito_ci_cache_all_targets_with_docker:-} == "true" ]]
   ) && \
   # Skip push when there is no environment
   ! ([[ ${taito_mode:-} == "ci" ]] && [[ ${taito_ci_no_env:-} == "true" ]]); then
  # Push docker image
  docker::push "${@}"
fi

if taito::is_current_target_of_type "function static_content"; then
  # Copy files on host and create a package
  docker::package "${@}"
fi

taito::call_next "${@}"
