#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

# Containers, functions and static assets are built with Docker
taito::skip_if_not "container function static_content" "${@}"

docker::push "${@}"
taito::call_next "${@}"
