#!/bin/bash -e
: "${taito_project:?}"

# Containers, functions and static assets are built with Docker
taito::skip_if_not "container function static_content" "${@}"

type=$1
if [[ $type == "tester" ]]; then
  file_suffix="-tester.docker"
  image_prefix="${taito_project}-"
  image_suffix="-tester:latest"
else
  file_suffix=".docker"
  image_prefix="TODO"
  image_suffix="TODO"
fi

files=$(ls -1 *${file_suffix})
if [[ "$files" ]]; then
  (
    taito::executing_start
    ls -1 *${file_suffix} | sed "s/${file_suffix}//" | xargs -L1 sh -c \
      "docker load --input \${0}${file_suffix}"
  )
fi

taito::call_next "${@}"
