#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

if [[ ${taito_target:-} ]] && [[ "${taito_targets:-}" != *"${taito_target}"* ]]; then
  # Do nothing
  :
elif [[ ${taito_target:-} ]]; then
  taito::skip_if_not container "${@}"
  docker-compose::expose_pod_and_container

  # Docker-compose uses directory name as image prefix by default
  dir_name="${taito_host_project_path:-/taito-cli}"
  # Leave only directory name
  dir_name="${dir_name##*/}"

  # echo "NOTE: You must run 'taito stop' first or else clean fails"
  compose_file=$(docker-compose::prepare_docker_compose_yaml false)
  taito::execute_on_host_fg "
    docker-compose -f $compose_file stop ${pod:?}
    docker-compose -f $compose_file rm --force ${pod:?}
    docker-compose -f $compose_file up --force-recreate --build --no-start ${pod:?}
    docker-compose -f $compose_file start ${pod:?}
  "
else
  # TODO [data | build] as arguments
  echo "Docker will remove images and volumes after taito-cli has exited"

  compose_file=$(docker-compose::prepare_docker_compose_yaml false)
  taito::execute_on_host_fg \
    "docker-compose -f $compose_file down --rmi 'local' --volumes --remove-orphans"
fi

taito::call_next "${@}"
