#!/bin/bash
: "${taito_util_path:?}"
: "${taito_plugin_path:?}"

if [[ ${taito_target:-} ]] && [[ "${taito_targets:-}" != *"${taito_target}"* ]]; then
  # Do nothing
  :
elif [[ ${taito_target:-} ]]; then
  # shellcheck disable=SC1090
  . "${taito_plugin_path}/util/determine-pod"

  # Docker-compose uses directory name as image prefix by default
  dir_name="${taito_host_project_path:-/taito-cli}"
  # Leave only directory name
  dir_name="${dir_name##*/}"

  # echo "NOTE: You must run 'taito stop' first or else clean fails"
  compose_file=$("$taito_plugin_path/util/prepare-compose-file" false)
  "${taito_util_path}/execute-on-host-fg" "
    docker-compose -f $compose_file stop ${pod:?}
    docker-compose -f $compose_file rm --force ${pod:?}
    docker-compose -f $compose_file up --force-recreate --build --no-start ${pod:?}
    docker-compose -f $compose_file start ${pod:?}
  "
else
  # TODO [data | build] as arguments
  echo "Docker will remove images and volumes after taito-cli has exited"

  compose_file=$("$taito_plugin_path/util/prepare-compose-file" false)
  "${taito_util_path}/execute-on-host-fg" \
    "docker-compose -f $compose_file down --rmi 'local' --volumes --remove-orphans"
fi && \

# Call next command on command chain
"${taito_util_path}/call-next" "${@}"
