#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"
: "${taito_target:?}"

source="${1:?}"
dest="${2:?}"

# shellcheck disable=SC1090
docker-compose::expose_pod_and_container

docker_cmd="docker cp ${source} ${pod:?}:${dest}"
taito::execute_on_host_fg "${docker_cmd}"

taito::call_next "${@}"
