#!/bin/bash
: "${taito_plugin_path:?}"
: "${taito_target:?}"

source="${1:?}"
dest="${2:?}"

# shellcheck disable=SC1090
. "${taito_plugin_path}/util/determine-pod" && \

docker_cmd="docker cp ${pod:?}:${source} ${dest}"
taito::execute_on_host_fg "${docker_cmd}"

taito::call_next "${@}"
