#!/bin/bash
: "${taito_util_path:?}"
: "${taito_plugin_path:?}"
: "${taito_target:?}"

source="${1:?}"
dest="${2:?}"

# shellcheck disable=SC1090
. "${taito_plugin_path}/util/determine-pod" && \

docker_cmd="docker cp ${pod:?}:${source} ${dest}"
"${taito_util_path}/execute-on-host-fg" "${docker_cmd}"

# Call next command on command chain
"${taito_util_path}/call-next" "${@}"
