#!/bin/bash
: "${taito_util_path:?}"

compose_file=$("$taito_plugin_path/util/prepare-compose-file" false)
"${taito_util_path}/execute-on-host-fg" "
  docker-compose -f $compose_file down -v
"

# Call next command on command chain
"${taito_util_path}/call-next" "${@}"
