#!/bin/bash

# TODO: duplicate code with env-apply

switches=" ${*} "

if [[ "${taito_env}" != "local" ]] || [[ "${switches}" != *" --clean "* ]]; then
  echo "Not cleaning database containers"
else
  echo "Cleaning database container(s)"
  (
    all=$("$taito_util_path/get-targets-by-type" database)
    databases=("${taito_target:-$all}")
    for database in ${databases[@]}
    do
      # TODO: duplicate code with clean

      # shellcheck disable=SC1090
      taito_target=$database
      . "${taito_plugin_path}/util/determine-pod"

      # Docker-compose uses directory name as image prefix by default
      dir_name="${taito_host_project_path:-/taito-cli}"
      # Leave only directory name
      dir_name="${dir_name##*/}"

      compose_file=$("$taito_plugin_path/util/prepare-compose-file" false)
      "${taito_util_path}/execute-on-host" "
        docker-compose -f $compose_file stop ${pod:?}
        docker-compose -f $compose_file rm --force ${pod:?}
        docker-compose -f $compose_file up --force-recreate --build --no-start ${pod:?}
        docker-compose -f $compose_file start ${pod:?}
      "
    done
    if [[ ${all} ]]; then
      sleep 15
      echo "Waiting for databases to start..."
      sleep 25
      echo "Done waiting"
    fi
  )
fi && \

# Call next command on command chain
"${taito_util_path}/call-next" "${@}"
