#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

taito::skip_if_not container "${@}"

if [[ ${taito_env} != 'local' ]]; then
  echo "Please use restart instead of kill"
  exit 0
fi

pod_index="${1}"

docker-compose::expose_pod_and_container false "${pod_index}"
taito::execute_on_host_fg "
  pod=${get_pod_command}
  docker kill \${pod:?}
"

taito::call_next "${@}"
