#!/bin/bash
: "${taito_util_path:?}"
: "${taito_plugin_path:?}"
: "${taito_project:?}"

# shellcheck disable=SC1090
. "${taito_plugin_path}/util/determine-pod" && \

"${taito_util_path}/execute-on-host-fg" "docker kill ${pod:?}" && \

# Call next command on command chain
"${taito_util_path}/call-next" "${@}"
