#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

taito::skip_if_not container "${@}"

pod_index="${1}"

docker-compose::expose_pod_and_container true "${pod_index}"
taito::execute_on_host_fg "
  pod=${get_pod_command}
  docker logs -f --tail 400 \${pod}
"

taito::call_next "${@}"


