#!/bin/bash
: "${taito_plugin_path:?}"

if [[ -n "${taito_target:-}" ]]; then
  # Restart only the container given as argument
  # shellcheck disable=SC1090
  . "${taito_plugin_path}/util/determine-pod"
  compose_file=$("$taito_plugin_path/util/prepare-compose-file")
  taito::execute_on_host_fg \
    "docker-compose -f $compose_file restart ${pod:?}"
else
  # Restart all containers
  "${taito_plugin_path}/util/start" "${@}" --restart
fi && \

taito::call_next "${@}"
