#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

if [[ -n "${taito_target:-}" ]]; then
  # Restart only the container given as argument
  # shellcheck disable=SC1090
  docker-compose::expose_pod_and_container
  compose_file=$(docker-compose::prepare_docker_compose_yaml)
  taito::execute_on_host_fg \
    "docker-compose -f $compose_file restart ${pod:?}"
else
  # Restart all containers
  docker-compose::start "${@}" --restart
fi

taito::call_next "${@}"
