#!/bin/bash -e
: "${taito_plugin_path:?}"

# shellcheck disable=SC1090
. "${taito_plugin_path}/util/determine-pod"

echo container: ${pod:?}

taito::execute_on_host \
  "docker ps; docker commit ${pod:?} ${pod:?}-savetus; echo ------"
taito::execute_on_host_fg \
  "docker image tag ${pod:?}-savetus ${pod:?}"

taito::call_next "${@}"
