#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

echo "Secrets in docker-compose.yaml:"
(taito::executing_start; cat docker-compose.yaml | grep -i "SECRET:\|PASSWORD:\|KEY:\|ID:")
echo

if [[ ${1} == "--save-as-taito-secrets" ]]; then
  save_to_disk=true
else
  save_to_disk=false
fi

secret_filter=
taito::export_secrets \
  docker-compose::get_secret_value \
  ${save_to_disk} \
  ${secret_filter}
taito::print_secret_values "${save_to_disk}"

taito::call_next "${@}"
