#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

taito::confirm "Save newly created secrets to ./secrets/${taito_env:?}" || \
  taito::skip_to_next "${@}"

taito::save_secrets \
  docker-compose::get_secret_value \
  docker-compose::put_secret_value

taito::call_next "${@}"
