#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

args=("${@}")

secret_filter=
save_to_disk=false
show_files=false

while [[ $# -gt 0 ]]; do
  key="$1"
  case ${key} in
  --save-as-taito-secrets)
    save_to_disk=true
    shift
    ;;
  --show-files)
    show_files=true
    shift
    ;;
  *)
    secret_filter="${key}"
    show_files=true
    shift
    ;;
  esac
done

if [[ ${taito_quiet:-} != "true" ]] &&
   [[ ${save_to_disk} != true ]] &&
   [[ ! ${secret_filter} ]]; then
  echo "Secrets in docker-compose.yaml:"
  (
    taito::executing_start
    cat docker-compose.yaml | grep -i "SECRET:\|PASSWORD:\|KEY:\|ID:"
  )
  echo
fi

taito::export_secrets \
  docker-compose::get_secret_value \
  ${save_to_disk} "${secret_filter}"
taito::print_secret_values ${save_to_disk} ${show_files} "${secret_filter}"

taito::call_next "${args[@]}"
