#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

compose_file=$(docker-compose::prepare_docker_compose_yaml false)
taito::execute_on_host_fg \
  "docker compose -f $compose_file ps"

taito::call_next "${@}"
