#!/bin/bash -e

options=" ${*} "
if [[ "${options}" == *" --down "* ]]; then
  echo "ERROR: 'taito stop --down' is deprecated. Run 'taito down' instead".
  exit 1
fi

if [[ -n "${taito_target:-}" ]]; then
  # Restart only the container given as argument
  # shellcheck disable=SC1090
  . "${taito_plugin_path}/util/determine-pod"
fi

compose_file=$("$taito_plugin_path/util/prepare-compose-file" false)
taito::execute_on_host_fg "
  docker-compose -f $compose_file stop ${pod:-}
"

taito::call_next "${@}"
