#!/bin/bash
: "${taito_util_path:?}"
: "${taito_plugin_path:?}"

echo "Setting default context for Kubernetes: ${taito_namespace:-kube-system}"
"${taito_plugin_path}/util/use-context"

# Call next command on command chain
"${taito_util_path}/call-next" "${@}"
