#!/bin/bash
: "${taito_plugin_path:?}"
: "${taito_namespace:?}"
: "${taito_project:?}"

source="${1:?}"
dest="${2:?}"

"${taito_plugin_path}/util/use-context" && \
. "${taito_plugin_path}/util/determine-pod-container"

(${taito_setv:?}; kubectl cp "${source}" "${pod}:${dest}" -c "${container}")

taito::call_next "${@}"
