#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"
: "${taito_namespace:?}"
: "${taito_project:?}"

source="${1:?}"
dest="${2:?}"

kubectl::use_context
kubectl::expose_pod_and_container

(${taito_setv:?}; kubectl cp "${source}" "${pod}:${dest}" -c "${container}")

taito::call_next "${@}"
