#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

taito::skip_if_not container "${@}"

if [[ $1 =~ ^[0-9]+$ ]]; then
  pod_index="${1}"
  source="${2:?}"
  dest="${3:?}"
else
  source="${1:?}"
  dest="${2:?}"
fi

kubectl::use_context
kubectl::expose_pod_and_container false "${pod_index}"
(taito::executing_start; kubectl cp "${pod}:${source}" "${dest}" -c "${container}")

taito::call_next "${@}"
