#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

echo "Checking application status"
kubectl::use_context

# Wait until all containers have been deployed
sleep 5
while kubectl get pods | grep "ContainerCreating" &> /dev/null; do
  echo "Waiting until all containers have been deployed"
  sleep 5
done
sleep 15

# Wait even longer in case of a temporary error
error_count=0
until [[ $error_count -ge 6 ]]; do
  pods=$(kubectl get pods)
  if echo "${pods}" | grep "BackOff\|Error\|Init" &> /dev/null; then
    echo "Some errors during deployment:"
    echo
    echo "${pods}"
    echo
    echo "Waiting errors to resolve..."
    sleep 15
  else
    break
  fi
  ((error_count=error_count+1))
done

if kubectl get pods | grep "BackOff\|Error\|Init" &> /dev/null; then
  echo "ERROR: Some of the containers failed to start"
  echo
  kubectl get pods
  exit 1
fi

taito::call_next "${@}"
