#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

taito::skip_if_not "container" "${@}"

kubectl::use_context
(
  taito::executing_start
  kubectl edit deployment \
    "${taito_project:?}-${taito_target_env:?}-${taito_target:?}"
)

taito::call_next "${@}"
