#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

source_port=$1
dest_port=${2:-$source_port}

if taito::is_current_target_of_type container; then
  kubectl::use_context
  kubectl::expose_pod_and_container
  # NOTE: --address 0.0.0.0 requires Kubernetes v1.13
  (${taito_setv:?}; kubectl port-forward "${pod}" "$source_port:$dest_port" --address 0.0.0.0)
fi

taito::call_next "${@}"
