#!/bin/bash -e
: "${taito_plugin_path:?}"

source_port=$1
dest_port=${2:-$source_port}

if taito::is_current_target_of_type container; then
  "${taito_plugin_path}/util/use-context"
  . "${taito_plugin_path}/util/determine-pod-container"
  # NOTE: --address 0.0.0.0 requires Kubernetes v1.13
  (${taito_setv:?}; kubectl port-forward "${pod}" "$source_port:$dest_port" --address 0.0.0.0)
fi

taito::call_next "${@}"
