#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"
: "${taito_namespace:?}"
: "${taito_project:?}"

kubectl::use_context

kubectl::expose_pods

(${taito_setv:?}; kubectl delete pod ${pods})

taito::call_next "${@}"
