#!/bin/bash
: "${taito_util_path:?}"
: "${taito_plugin_path:?}"
: "${taito_namespace:?}"
: "${taito_project:?}"

"${taito_plugin_path}/util/use-context" && \

. "${taito_plugin_path}/util/determine-pods"

(${taito_setv:?}; kubectl delete pod ${pods}) && \

# Call next command on command chain
"${taito_util_path}/call-next" "${@}"
