#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

taito::skip_if_not container "${@}"

pod_index="${1}"

kubectl::use_context
if [[ $pod_index ]]; then
  kubectl::expose_pod_and_container false "${pod_index}"
  (taito::executing_start; kubectl delete pod "${pod:?}")
else
  kubectl::expose_pods
  (taito::executing_start; kubectl delete pod ${pods})
fi

taito::call_next "${@}"
