#!/bin/bash
: "${taito_util_path:?}"
: "${taito_plugin_path:?}"
: "${taito_namespace:?}"
: "${taito_project:?}"

container="${1}"

"${taito_plugin_path}/util/use-context"

DETERMINE_FAILED_POD=true
. "${taito_plugin_path}/util/determine-pod-container"

echo pod: "${pod}"
echo container: "${container}"

if [[ -z "${pod}" ]]; then
  echo
  echo "kubectl: Please give pod name as argument:"
  echo
  (${taito_setv:?}; kubectl get pods)
else
  # Kubernetes
  echo
  echo -e "${H2s}Desciption${H2e}"
  (${taito_setv:?}; kubectl describe pod "${pod}")
  echo
  echo
  echo -e "${H2s}Logs${H2e}"
  if ! (${taito_setv:?}; kubectl logs -f --tail=400 "${pod}" "${container}"); then
    exit 1
  fi
fi

# Call next command on command chain
"${taito_util_path}/call-next" "${@}"
