#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"
: "${taito_namespace:?}"
: "${taito_project:?}"

container="${1}"

kubectl::use_context

DETERMINE_FAILED_POD=true
kubectl::expose_pod_and_container

echo pod: "${pod}"
echo container: "${container}"

if [[ -z "${pod}" ]]; then
  echo
  echo "kubectl: Please give pod name as argument:"
  echo
  (${taito_setv:?}; kubectl get pods)
else
  # Kubernetes
  echo
  echo -e "${H2s}Desciption${H2e}"
  (${taito_setv:?}; kubectl describe pod "${pod}")
  echo
  echo
  echo -e "${H2s}Logs${H2e}"
  if ! (${taito_setv:?}; kubectl logs -f --tail=400 "${pod}" "${container}"); then
    exit 1
  fi
fi

taito::call_next "${@}"
