#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"
: "${taito_namespace:?}"
: "${taito_project:?}"
: "${taito_target_env:?}"

kubectl::use_context

echo "kubectl: TODO rolling restart instead of kill"
if [[ -n "${taito_target:-}" ]]; then
  # Restart only the container given as argument
  kubectl::expose_pod_and_container
  (${taito_setv:?}; kubectl delete pod "${pod}")
else
  (${taito_setv:?}; kubectl delete pods -l release="${taito_project}-${taito_target_env}")
fi

taito::call_next "${@}"
