#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"
: "${taito_namespace:?}"

flag=${1}

kubectl::use_context

save_to_disk=false
if [[ "${flag}" == "--save-as-taito-secrets" ]]; then
  save_to_disk=true
else
  kubectl get secrets
  echo 'Showing secret values from Kubernetes:'
  echo
fi

kubectl::export_secrets "${save_to_disk}"

# Print secret values
rm taito-secrets &> /dev/null || :
secret_index=0
secret_names=(${taito_secret_names})
for secret_name in "${secret_names[@]}"
do
  taito::expose_secret_by_index ${secret_index}

  if [[ "${flag}" == "--save-as-taito-secrets" ]]; then
    if [[ ${secret_value} ]]; then
      echo "export ${secret_value_var}=\"${secret_value}\"; " >> taito-secrets
    fi
  else
    echo "Secret ${secret_name}:"
    echo "${secret_value:-HIDDEN}"
    echo
  fi
  secret_index=$((${secret_index}+1))
done

taito::call_next "${@}"
