#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

kubectl::use_context

echo "Exporting secrets to ${taito_tmp_secrets_dir:?}"
while [[ $# -gt 0 ]]; do
  secret_filter="$1"
  echo "${secret_filter}"
  taito::export_secrets kubectl::get_secret_value true "${secret_filter}"
  shift
done

taito::call_next "${@}"
