#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

kubectl::use_context

secret_filter=
save_to_disk=false
show_files=false

while [[ $# -gt 0 ]]; do
  key="$1"
  case ${key} in
  --save-as-taito-secrets)
    save_to_disk=true
    shift
    ;;
  --show-files)
    show_files=true
    shift
    ;;
  *)
    secret_filter="${key}"
    show_files=true
    shift
    ;;
  esac
done

if [[ ${save_to_disk} == "false" ]] && [[ ! ${secret_filter} ]]; then
  kubectl get secrets
  echo 'Showing secret values from Kubernetes:'
  echo
fi

taito::export_secrets \
  kubectl::get_secret_value \
  ${save_to_disk} "${secret_filter}"
taito::print_secret_values ${save_to_disk} ${show_files} "${secret_filter}"

taito::call_next "${@}"
