#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

resource=${1}   # cpu or mem (cpu by default)
name=${2}       # e.g. node, namespace, or pod

sort_key=2 # cpu
if [[ ${resource} == "mem" ]]; then
  sort_key=3
fi

echo "This may take a while..."
echo
kubectl::use_context

if [[ ${name} ]]; then
  # Do not filter by namespace if name was given
  kubectl get pods -o wide --no-headers -A \
  | grep "${name}" \
  | awk '{print $1" "$2}' \
  | xargs -n2 kubectl top pods --no-headers --namespace \
  | sort --key ${sort_key} --numeric --reverse \
  | xargs printf '%-60s %-6s %-6s\n'
else
  kubectl get pods -o wide --no-headers \
  | awk '{print $1}' \
  | xargs -n1 kubectl top pods --no-headers \
  | sort --key ${sort_key} --numeric --reverse \
  | xargs printf '%-60s %-6s %-6s\n'
fi

taito::call_next "${@}"
