#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

if [[ ${taito_secrets:-} ]] && taito::confirm "Generate secrets"; then
  generate-secrets::create_and_export true
fi

taito::call_next "${@}"
