#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

name="${1}"

echo "Cleaning up temporary secret files from disk"
generate-secrets::delete_temporary_files

taito::call_next "${@}"
