#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

# TODO: move to Terraform module
if taito::confirm "Create Cloud Build worker pool (optional)" no; then

  network_id=$(cd terraform > /dev/null && terraform output network_id 2> /dev/null)
  echo "Using network name: ${network_name}"

  gcloud --project "${taito_zone:?}" beta builds worker-pools create \
    "${taito_zone:?}" \
    --peered-network="${network_id}" \
    --region="us-central1"
    # TODO: "${taito_provider_region:?}" (Other regions not yet supported)
fi

taito::call_next "${@}"
