#!/bin/bash
: "${taito_plugin_path:?}"

name=${1}

if [[ -n "${kubernetes_name:-}" ]]; then
  if taito::confirm_execution "gcp-build-notifications" "${name}" \
    "Destroy gcp build notifications"
  then
    "${taito_plugin_path}/util/teardown-build-slack-notifications"
  fi
fi && \

taito::call_next "${@}"
