#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

name=${1}

if [[ -n "${kubernetes_name:-}" ]]; then
  if taito::confirm_execution "gcp-build-notifications" "${name}" \
    "Destroy gcp build notifications"
  then
    gcp-zone::teardown-cloud-build-slack-notifications
  fi
fi

taito::call_next "${@}"
