#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

if [[ ${taito_uptime_provider:-} == "gcp" ]] &&
   [[ ! ${taito_uptime_channels:-} ]] &&
   taito::confirm "Configure uptime monitoring channels for Google StackDriver"; then

  # See: https://stackoverflow.com/questions/54884815/obtain-slack-auth-token-for-terraform-google-monitoring-notification-channel-res
  echo
  echo "Monitoring notification channels are currently configured manually instead of"
  echo "using Terraform, because of Slack auth token handling."
  echo
  echo "Add the following ${taito_messaging_app:-} channels with StackDriver web gui"
  echo "(Alerting -> Edit notification channels):"
  echo
  echo "- ${taito_messaging_builds_channel:-}"
  echo "- ${taito_messaging_critical_channel:-}"
  echo "- ${taito_messaging_monitoring_channel:-}"
  echo
  echo "Press enter to open StackDriver workspace settings in browser"
  read -r
  taito::open_browser "https://app.google.stackdriver.com/settings/accounts/notifications/slack?project=${taito_zone:?}"
  echo "Press enter once done"
  read -r
  echo
  gcloud -q --project "${taito_zone}" alpha monitoring channels list ||
    echo "ERROR: Listing channels failed."
  echo
  echo "Channels are shown above. Configure taito_uptime_channels setting in"
  echo "taito-config.sh using the ${taito_messaging_critical_channel} channel name"
  echo "For example:"
  echo
  echo "taito_uptime_channels=\"projects/${taito_zone}/notificationChannels/1234567890\""
  echo
  echo "Press enter once done"
  read -r
fi

taito::call_next "${@}"
