#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

if [[ ${taito_uptime_provider:-} != "gcp" ]]; then
  echo "Not using GCP for uptime monitoring"
elif [[ ${taito_uptime_channels:-} ]]; then
  echo "Uptime channels already configured"
elif taito::confirm "Configure uptime monitoring channels for Google Cloud"; then
  # TODO: Move to Terraform module
  # See: https://stackoverflow.com/questions/54884815/obtain-slack-auth-token-for-terraform-google-monitoring-notification-channel-res
  echo
  echo "Monitoring notification channels are currently configured manually instead of"
  echo "using Terraform, because of Slack auth token handling."
  echo
  echo "Add the following ${taito_messaging_app:-} channels with the Google Cloud web console:"
  echo
  echo "- ${taito_messaging_builds_channel:-}"
  echo "- ${taito_messaging_critical_channel:-}"
  echo "- ${taito_messaging_monitoring_channel:-}"
  echo
  echo "Press enter to open Google Cloud notification channel settings in web browser"
  read -r
  taito::open_browser "https://console.cloud.google.com/monitoring/alerting/notifications?project=${taito_zone:?}"
  echo "Press enter once done"
  read -r
  echo
  gcloud -q --project "${taito_zone}" beta monitoring channels list ||
    echo "ERROR: Listing channels failed."
  echo
  echo "----------------------------------------------------------------------------"
  echo "Channels are shown above. Configure taito_uptime_channels setting in"
  echo "taito-config.sh using the ${taito_messaging_critical_channel} channel name. For example:"
  echo
  echo "taito_uptime_channels=\"projects/${taito_zone}/notificationChannels/1234567890\""
  echo "----------------------------------------------------------------------------"
  echo
  echo "Press enter once done"
  read -r
fi

taito::call_next "${@}"
