#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

( [[ -n "${kubernetes_name:-}" ]] && \
  taito::confirm "Configure gcp build notifications"
) || taito::skip_to_next "${@}"

gcp-zone::setup_cloud_build_slack_notifications

taito::call_next "${@}"
