#!/bin/bash -e
# shellcheck source=../gcp/lib/all.bash
. "${taito_plugin_path:?}/../gcp/lib/all.bash"
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

( [[ ${kubernetes_name:-} ]] && \
  taito::confirm "Authenticate to Kubernetes ${kubernetes_name:-}"
) || taito::skip_to_next "${@}"

gcp::authenticate_on_kubernetes

taito::call_next "${@}"
