#!/bin/bash -e

name=${1}

if [[ -n "${kubernetes_name:-}" ]]; then
  if taito::confirm_execution "gcp-kubectl" "${name}" \
    "Execute Kubernetes cluster maintenance"
  then
      echo "TODO confirm and upgrade Kubernetes master"
      echo "TODO confirm and upgrade Kubernetes nodes"
  fi
fi

taito::call_next "${@}"
