#!/bin/bash -e

taito::execute_on_host_fg "
if git rev-parse --is-inside-work-tree &> /dev/null; then
  taito::print_title "Version control conventions"
  echo
  echo 'Environment branches:'
  echo '- Branch naming: demo, dev, test, uat, stag, canary, master.'
  echo '- Environment branches should be merged to one another in the following'
  echo '  order: demo -> dev -> test -> uat/qa -> stag -> canary -> master.'
  echo '- Environment branches should be merged using fast-forward only.'
  echo '- dev is the only environment branch that you should commit changes to.'
  echo
  echo 'Feature branches:'
  echo '- Naming with feat/ prefix, for example: feat/delete-user.'
  echo '- Feature branches are created from dev branch and merged back to it'
  echo '  using non-fast-forward to keep a clear feature branch history.'
  echo '- You should rebase your feature branch with the dev branch before'
  echo '  merge. It is recommended to squash some of your commits during rebase'
  echo '  to keep a clean version history.'
  echo '- You should delete a feature branch once it is no longer needed.'
  echo
  echo 'Hotfix branches:'
  echo '- TODO'
  echo
fi
"

taito::call_next "${@}"
