#!/bin/bash -e

dest="${taito_branch:-dev}"

taito::execute_on_host_fg "\
if git rev-parse --is-inside-work-tree > /dev/null; then
  set -e
  if [[ \"${1}\" ]]; then
    feature=\"feat/${1}\"
  else
    feature=\$(git symbolic-ref --short HEAD)
  fi

  echo \"Making a pull request for merging \${feature} to ${dest}\"
  read -t 1 -n 1000 discard || :
  read -p \"Do you want to continue? [Y/n] \" -n 1 -r confirm
  echo
  if ! [[ \${confirm} =~ ^[Yy]*$ ]]; then
    exit 130
  fi
  read -t 1 -n 1000 discard || :
  read -p \"Rebase branch \${feature} before making the pull request? [Y/n] \" -n 1 -r rebase
  git checkout \${feature}
  if [[ \${rebase} =~ ^[Yy]*$ ]]; then
    git fetch --all
    git rebase -i origin/${dest}
  fi
  git push --no-verify -u origin \${feature}
  git checkout -
  echo
  echo 'TODO: implement PR using the hub cli.'
  echo
  echo \"Make the pull request with your web browser. Press enter to open browser.\"
  read -r
  taito ${taito_options:-} open git

  if [[ \"${taito_ci_provider:-}\" == \"local\" ]]; then
    echo
    echo ----------------------------------------------------------------------
    echo TIP: Run \\'taito ci run:${taito_target_env}\\' to execute CI/CD locally.
    echo ----------------------------------------------------------------------
    echo
  fi
fi
"

taito::call_next "${@}"
