#!/bin/bash -e

source="${taito_branch:-dev}"

taito::execute_on_host_fg "
if git rev-parse --is-inside-work-tree &> /dev/null
   ! git checkout feat/${1} 2> /dev/null
   [[ \"${1}\" ]]; then
  dest=\"feat/${1}\"
  echo \"Creating a new branch: \${dest}\"
  read -t 1 -n 1000 discard || :
  read -p \"Do you want to continue? [Y/n] \" -n 1 -r confirm
  echo
  if ! [[ \${confirm} =~ ^[Yy]*$ ]]; then
    echo Cancelled
    exit 130
  fi
  git checkout ${source}
  git pull
  git checkout -b \${dest}
  echo
  echo TODO explain when to push to remote repository
  read -t 1 -n 1000 discard || :
  read -p \"Push the \${dest} branch to the remote repository? [y/N] \" -n 1 -r confirm
  echo
  if [[ \${confirm} =~ ^[Yy]$ ]]; then
    git push --no-verify -u origin \${dest} || \
      echo NOTE: Push failed. Fix errors and the run \'push -u origin \${dest}\'.
  fi
fi
"

taito::call_next "${@}"
