#!/bin/bash -e
: "${taito_util_path:?}"

"${taito_util_path}/execute-on-host-fg" "
if git rev-parse --is-inside-work-tree &> /dev/null; then
  git reset ${*}
fi
"

# Call next command on command chain
"${taito_util_path}/call-next" "${@}"
