#!/bin/bash -e

tag="${1}"

taito::execute_on_host_fg "
if git rev-parse --is-inside-work-tree &> /dev/null; then
  set -e
  git tag -d ${tag}
  git push origin :refs/tags/${tag}
fi
"

taito::call_next "${@}"
