#!/bin/bash -e

if [[ ${taito_mode:-} == "ci" ]] && \
   [[ ${taito_container_registry:-} ]]; then
  echo "Starting dockerd (required for Docker builds on AWS CodeBuild)"
  (
    taito::executing_start
    nohup /usr/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
  )
fi

taito::call_next "${@}"
