#!/bin/bash -e
: "${taito_setv:?}"
: "${taito_plugin_path:?}"

name=${1}

# Delete Helm charts
if [[ -d "./helm" ]]; then
  "${taito_cli_path}/plugins/kubectl/util/use-context"
  charts=($(cd helm && ls))
  for chart in ${charts[@]}
  do
    if taito::confirm_execution "${chart}" "${name}" \
      "Delete helm chart ${chart} from Kubernetes"
    then
      echo "- Deleting chart ${chart} using Helm"
      (
        ${taito_setv}
        "${taito_plugin_path}/../helm/util/helm" delete "${chart}" --purge
      )
    fi
  done
fi

taito::call_next "${@}"
