#!/bin/bash -e
# shellcheck source=../helm/lib/all.bash
. "${taito_plugin_path:?}/../hell/lib/all.bash"
# shellcheck source=../kubectl/lib/context.bash
. "${taito_plugin_path:?}/../kubectl/lib/context.bash"

kubectl::use_context
helm::run list

taito::call_next "${@}"
