#!/bin/bash -e
# shellcheck source=../aws/lib/all.bash
. "${taito_cli_path:?}/plugins/aws/lib/all.bash"
: "${taito_command:?}"

if [[ $taito_command == "zone-"* ]]; then
  echo
  echo -e "${taito_command_context_prefix:-}${H1s}aws-zone${H1e}"
  aws::authenticate
fi

taito::call_next "${@}"
