#!/bin/bash
: "${taito_env:?}"

name=${1}

if taito::confirm_execution "terraform" "${name}" \
  "Destroy zone by running terraform scripts"
then
  (
    export TF_LOG_PATH="./terraform.log"
    # shellcheck disable=SC1090
    . "${taito_cli_path}/plugins/terraform/util/env" && \
    cd "./terraform" && \
    terraform init && \
    if [[ -f import_state ]]; then
      ./import_state
    fi && \
    terraform destroy
  )
fi && \

taito::call_next "${@}"
