#!/bin/bash -e

taito::confirm \
  "Replace placeholders with real values in taito_config.sh and terraform/*" || \
  taito::skip_to_next "${@}"

(
  cd terraform || exit 1

  # For AWS: determine hex string for region from database endpoint URL
  if [[ ${taito_provider:-} == "aws" ]]; then
    database=
    instance=
    if [[ ${postgres_instances:-} ]]; then
      database=postgres
      instance=${postgres_instances:-}
    elif [[ ${mysql_instances:-} ]]; then
      database=mysql
      instance=${mysql_instances:-}
    fi
    if [[ ${database} ]] && \
       [[ ${taito_provider_region_hexchars:-} == "TAITO_PROVIDER_REGION_HEXCHARS" ]]; then
      echo "Detemining hexadecimal string for region ${taito_provider_region:?}"
      hexchars=$(terraform output ${database}_instance_endpoint | \
        sed "s/$instance\\.\\(.*\\)\\.$taito_provider_region.*/\\1/" \
      )
      if [[ $hexchars ]]; then
        export taito_provider_region_hexchars=$hexchars
        echo "$hexchars"
      else
        echo "WARNING: Could not determine hexadecimal string"
      fi
      echo
    fi
    echo "Detemining bastion public IP"
    taito_zone_bastion_public_ip=$(terraform output bastion_public_ip || :)
  fi

  echo "Replacing hardcoded example values in taito_config and terraform/*"
  echo TAITO_ORGANIZATION
  sed -i "s/TAITO_ORGANIZATION/${taito_organization:?}/g" ./*.tf
  if [[ ${taito_provider_region_hexchars:-} ]]; then
    echo TAITO_PROVIDER_REGION_HEXCHARS
    sed -i "s/TAITO_PROVIDER_REGION_HEXCHARS/$taito_provider_region_hexchars/g" ./*.tf ../taito-config.sh
  fi
  echo TAITO_PROVIDER_REGION
  sed -i "s/TAITO_PROVIDER_REGION/$taito_provider_region/g" ./*.tf
  if [[ ${taito_zone_bastion_public_ip} ]]; then
    echo TAITO_ZONE_BASTION_PUBLIC_IP
    sed -i "s/TAITO_BASTION_PUBLIC_IP/$taito_zone_bastion_public_ip/g" ../taito-config.sh
  fi
  if [[ ${taito_zone_state_bucket:-} ]]; then
    echo TAITO_ZONE_STATE_BUCKET
    sed -i "s/TAITO_ZONE_STATE_BUCKET/$taito_zone_state_bucket/g" ./*.tf
  fi
  if [[ ${mysql_instances:-} ]]; then
    echo MYSQL_INSTANCES
    sed -i "s/MYSQL_INSTANCES/$mysql_instances/g" ./*.tf
  fi
  if [[ ${postgres_instances:-} ]]; then
    echo POSTGRES_INSTANCES
    sed -i "s/POSTGRES_INSTANCES/$postgres_instances/g" ./*.tf
  fi
  echo
)

taito::call_next "${@}"
