#!/bin/bash -e
# shellcheck source=../kubectl/lib/context.bash
. "${taito_plugin_path:?}/../kubectl/lib/context.bash"
# shellcheck source=../kubectl/lib/secret.bash
. "${taito_plugin_path:?}/../kubectl/lib/secret.bash"

taito::confirm "Add labels for kube-system namespace" ||
  taito::skip_to_next "${@}"

kubectl::use_context
kubectl label namespace kube-system networking/namespace=kube-system

taito::call_next "${@}"
