#!/bin/bash -e
# shellcheck source=../kubectl/lib/context.bash
. "${taito_plugin_path:?}/../kubectl/lib/context.bash"
# shellcheck source=../kubectl/lib/secret.bash
. "${taito_plugin_path:?}/../kubectl/lib/secret.bash"

if taito::confirm "Add Argo Events custom resource definitions" no; then
  kubectl::use_context
  kubectl apply -k /tools/argo-events/crds
fi

if taito::confirm "Add Argo Workflows custom resource definitions" no; then
  kubectl::use_context
  kubectl apply -k /tools/argo-workflows/crds
fi

taito::call_next "${@}"
