#!/bin/bash -e
# shellcheck source=../kubectl/lib/context.bash
. "${taito_plugin_path:?}/../kubectl/lib/context.bash"
# shellcheck source=../kubectl/lib/secret.bash
. "${taito_plugin_path:?}/../kubectl/lib/secret.bash"

if [[ ${taito_secrets:-} ]] && taito::confirm "Save secrets to Kubernetes"; then
  kubectl::use_context
  taito::save_secrets \
    kubectl::get_secret_value \
    kubectl::put_secret_value
fi

taito::call_next "${@}"
