#!/bin/bash -e
# shellcheck source=../kubectl/lib/context.bash
. "${taito_plugin_path:?}/../kubectl/lib/context.bash"

kubectl::use_context

taito::print_title "Cluster"
kubectl get componentstatus

taito::print_title "Nodes"
kubectl describe nodes

taito::print_title "Top nodes"
kubectl top nodes 2> /dev/null

taito::print_title "Ingresses"
kubectl get ingress --all-namespaces

taito::print_title "Services"
kubectl get services --all-namespaces

taito::print_title "Pods"
kubectl get pods --all-namespaces

taito::print_title "Top pods"
kubectl top pods --all-namespaces 2> /dev/null

taito::print_title "Load balancer addresses"
lb_ips="$(kubectl get services -o=custom-columns=LOAD_BALANCER_IP:.status.loadBalancer.ingress[0].ip,LOAD_BALANCER_AP:.status.loadBalancer.ingress[0].hostname \
  --no-headers --all-namespaces 2> /dev/null | grep -v "<none>.*<none>" | sed s/\\s*\<none\>\\s*//g)"
if [[ ${lb_ips} ]]; then
  echo "${lb_ips}"
  echo
  echo "Your load balancer addresses are presented above. You should configure"
  echo "DNS for them, and also set 'taito_default_domain' in taito-config.sh,"
  echo "if you have not done so already. Example DNS entry:"
  echo
  if [[ ${#lb_ips} -ge 20 ]]; then
    echo "  CNAME  *.${taito_default_domain:-mydomain.com}  ->  ${lb_ips}"
  else
    echo "      A  *.${taito_default_domain:-mydomain.com}  ->  ${lb_ips}"
  fi
  echo
else
  echo "WARNING: Your Kubernetes cluster does not seem to contain any load balancer"
  echo "IP addresses. How you installed nginx-ingress?"
  echo
fi

taito::call_next "${@}"
