#!/bin/bash -e

# TODO clean this mess. duplicate code in clean, psql and sqitch

username="${1}"
flags="${2}"
command="${3:-psql}"

# TODO: duplicate logic with mysql and mysqldump
# TODO: needs refactoring

psql_username="${database_name}_app"
if [[ "${database_username:-}" ]]; then
  psql_username="${database_username}"
fi
psql_password="${database_password:-$taito_default_password}"

if [[ "${username}" != "" ]]; then
  psql_username="${username}"
  psql_password=""
elif [[ "${taito_env}" != "local" ]]; then
  . "${taito_util_path}/database_username_password.bash"
  if [[ "${database_build_username}" ]] && \
     [[ "${database_build_password}" ]]; then
    psql_username="${database_build_username}"
    psql_password="${database_build_password}"
  fi
fi

(
  export PGPASSWORD="${psql_password}"
  ${taito_setv:?}
  ${command} -h "${database_host}" \
  -p "${database_port}" \
  -d "${database_name}" \
  -U "${psql_username}" \
  ${flags}
)
