#!/bin/bash -e
: "${taito_env:?}"
: "${taito_plugin_path:?}"

echo "TODO implement with gsutil"
echo "bucket: ${taito_target}"
echo "source_env: ${taito_env}"
echo "dest_env: ${taito_dest_env}"
echo "source: ${1}"
echo "dest: ${2}"
