#!/bin/bash
: "${taito_plugin_path:?}"

if [[ "${link_global_urls:-}${link_urls:-}" == *" conventions="* ]]; then
  echo "Press enter to open the software development conventions page"
  read -r
  "${taito_plugin_path}/util/open" "conventions" "open" "browser" ":"
fi

taito::call_next "${@}"
