#!/bin/bash -e
# shellcheck source=../azure/lib/all.bash
. "${taito_cli_path:?}/plugins/azure/lib/all.bash"

( [[ ${kubernetes_name:-} ]] && \
    taito::confirm "Authenticate to Kubernetes ${kubernetes_name:-}"
) || taito::skip_to_next "${@}"

echo "Authenticating"
azure::authenticate_on_kubernetes

taito::call_next "${@}"
