#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

if [[ "${database_type:-}" == "pg" ]] || [[ -z "${database_type}" ]]; then
  username="${1}"
  postgres::connect "${username}"
fi

taito::call_next "${@}"
