#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

if [[ ${database_type:-} == "pg" ]] || [[ -z "${database_type}" ]]; then
  if taito::confirm "Create postgres database ${database_name}"; then
    postgres::create_database
  fi
fi

taito::call_next "${@}"
