#!/bin/bash
: "${taito_plugin_path:?}"
: "${taito_env:?}"
: "${database_name:?}"
: "${database_host:?}"
: "${database_port:?}"

if [[ "${database_type:-}" == "pg" ]] || [[ -z "${database_type}" ]]; then
  username="${1}"
  "${taito_plugin_path}/util/psql" "${username}"
fi && \

taito::call_next "${@}"
