#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

confirm_default=$([[ $taito_mode == "ci" ]] && echo 'yes' || echo 'no')

if [[ ${database_type:-} == "pg" ]] || [[ -z "${database_type}" ]]; then
  if taito::confirm "Delete postgres database ${database_name}" ${confirm_default}; then
    postgres::drop_database
  fi
fi

taito::call_next "${@}"
