#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

if [[ ${database_type:-} == "pg" ]] || [[ -z "${database_type}" ]]; then
  dump_file="${1:?}"
  username=$2

  echo "Dumping database ${database_name:?} to ${dump_file}. Please wait."
  postgres::connect "${username}" " --no-owner --no-privileges -f ${dump_file}" "pg_dump"
fi

taito::call_next "${@}"
