#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

if [[ ${database_type:-} == "pg" ]] || [[ -z "${database_type}" ]]; then
  dump_file="${1:?}"
  username=$2

  # REFACTOR: args handling
  if [[ ${username} == "--" ]]; then
    username=
  fi
  tool_options="${*}"
  if [[ ${tool_options} == *" -- "* ]]; then
    tool_options="${tool_options##* -- }"
  else
    tool_options=""
  fi

  echo "Dumping database ${database_name:?} to ${dump_file}. Please wait."
  # NOTE: Dumping data as inserts because sometimes COPY doesn't seem to not
  # work correctly with empty columns
  postgres::connect \
    "${username}" \
    " ${tool_options} --no-owner --no-privileges --blobs --inserts -f ${dump_file}" \
    "pg_dump"
fi

taito::call_next "${@}"
