#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

if [[ ${database_type:-} == "pg" ]] || [[ -z "${database_type}" ]]; then
  filename="${1:?Filename not given}"
  username="${2}"

  # REFACTOR: args handling
  if [[ ${username} == "--" ]]; then
    username=
  fi
  tool_options="${*}"
  if [[ ${tool_options} == *" -- "* ]]; then
    tool_options="${tool_options##* -- }"
  else
    tool_options=""
  fi

  echo "Importing ${1}"
  (
    # TODO: change to current path (subdir where user was located on host)
    # cd "${taito_current_path:?}"
    flags="-f ${filename} ${tool_options}"
    postgres::connect "${username}" "${flags}" psql
  )
  echo "Done"
fi

taito::call_next "${@}"
