#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

# TODO: duplicate code with env-apply

if [[ "${taito_env}" == "local" ]]; then
  echo "Skipping database recreate for local environment"
else
  echo "Creating database(s)"
  (
    all=$(taito::print_targets_of_type database)
    databases=("${taito_target:-$all}")
    for database in ${databases[@]}; do
      export taito_target="${database}"
      taito::export_database_config "${database}"

      if [[ "${database_type:-}" == "pg" ]] || [[ -z "${database_type}" ]]; then
        if taito::confirm "Recreate postgres database ${database_name}"; then
          # Create a subshell to contain password
          (
            export database_username=${database_master_username:-postgres}
            echo "HINT: You can get the ${database_username} user password from:"
            echo "${database_master_password_hint:-}"
            postgres::ask_and_expose_password
            postgres::drop_database
            postgres::create_database
          )
        fi
      fi
    done
  )
fi

taito::call_next "${@}"
