#!/bin/bash
: "${taito_util_path:?}"
: "${taito_plugin_path:?}"

name=${1}

# TODO: duplicate code with env-apply

if [[ "${taito_env}" == "local" ]]; then
  echo "Skipping database recreate for local environment"
else
  echo "Creating database(s)"
  (
    all=$("$taito_util_path/get-targets-by-type" database)
    databases=("${taito_target:-$all}")
    for database in ${databases[@]}
    do
      export taito_target="${database}"
      . "${taito_util_path}/read-database-config" "${database}" && \

      if [[ "${database_type:-}" == "pg" ]] || [[ -z "${database_type}" ]]; then
        if "${taito_util_path}/confirm-execution" "${database_name}" "${name}" \
          "Recreate postgres database ${database_name}"
        then
          # Create a subshell to contain password
          (
            export database_username=${database_master_username:-postgres}
            echo "HINT: You can get the ${database_username} user password from:"
            echo "${database_master_password_hint:-}"
            . "${taito_plugin_path}/util/ask-password" && \
            "${taito_plugin_path}/util/drop-database" && \
            "${taito_plugin_path}/util/create-database"
          )
        fi
      fi
    done
  )
fi && \

# Call next command on command chain
"${taito_util_path}/call-next" "${@}"
