#!/bin/bash -e

project=${taito_resource_namespace:?}

if [[ -z ${project} ]]; then
  echo "ERROR: GCP project variable not set" >&2
  exit 1
fi;

# There's ongoing issue with --limit being applied before --sort-by
gcloud batch jobs list \
  --project="$project" \
  --sort-by="~createTime" \
  --format="table(name.basename():label=JOB_ID, status.state:label=STATUS, createTime.date():label=CREATED)" \
  | head -n 15

taito::call_next "${@}"
