#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

: "${template_default_source_git:?}"

export template="${1:?Template not given}"
branch=${2:-master}

export template_name="${template}"
export template_project_path="${PWD}"
export template_source_git="${template_default_source_git}"
export template_dest_git="${template_default_dest_git:?}"

# TODO read template_source_git from template_name if it has been given as prefix

echo
if [[ ${taito_organization_param:-} ]]; then
  echo "Migrating project with '${taito_organization_param:-}' settings"
else
  echo "Migrating project with personal default settings"
fi
template-global::ask_and_export_details

# Validate current git repository name
current_vc_url=$(git config --get remote.origin.url)
dest_vc_url="${template_dest_git:?}/${taito_vc_repository:?}.git"
if [[ $current_vc_url != "$dest_vc_url" ]]; then
  echo "WARNING: Git url '$current_vc_url' does not match with '$dest_vc_url'!"
  echo "You should rename the git repository first and only then run the migration."
  taito::confirm "Continue with the old git repository name?" no || exit
fi

# Clone template git repo to a temporary template-tmp directory
# and then continue the migration there.
echo
echo "Please wait."
rm -rf "./template-tmp"
mkdir "./template-tmp"
taito::execute_on_host_fg "
  set -e
  export GIT_PAGER=''
  git clone -q -b ${branch} --single-branch --depth 1 \
    ${template_source_git}/${template}.git ./template-tmp/${template}
  rm -rf ./template-tmp/${template}/.git
  yes | cp ./template-tmp/${template}/taito*config.sh .
  yes | cp -r ./template-tmp/${template}/scripts/taito ./scripts
  echo 'export template=${template}' >> _template-config.sh
  echo 'export template_name=${template}' >> _template-config.sh
  echo 'export template_source_git=${template_source_git}' >> _template-config.sh
  echo 'export template_dest_git=${template_dest_git}' >> _template-config.sh
  echo 'export template_project_path=${PWD}' >> _template-config.sh
  echo 'export taito_template=${template}' >> _template-config.sh
  echo 'export taito_company=${taito_company:?}' >> _template-config.sh
  echo 'export taito_family=${taito_family:-}' >> _template-config.sh
  echo 'export taito_application=${taito_application:?}' >> _template-config.sh
  echo 'export taito_suffix=${taito_suffix:-}' >> _template-config.sh
  echo 'export taito_vc_repository=${taito_vc_repository}' >> _template-config.sh
  taito ${taito_options:-} project migrate continue
"

taito::call_next "${@}"
