#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

. _template-config.sh
rm -f _template-config.sh
rm -f taito-config.sh

: "${template_default_source_git:?}"
: "${template_project_path:?}"

function cleanup {
  # Delete temporary template files and configs
  rm -rf ./template-tmp
}
trap cleanup EXIT

# Execute migrate script of template
(
  set -e
  cd "${template_project_path:?}/template-tmp/${template:?}"
  template-global::init migrate
)

taito::execute_on_host_fg "
  if ! git show-ref --tags | grep 'refs/tags/v' &> /dev/null; then
    git tag v0.0.0 && git push -q origin v0.0.0
  fi
"

taito::call_next "${@}"
