#!/bin/bash -e

template_default_zone_source_git=${template_default_zone_source_git:-git@github.com:TaitoUnited/taito-templates//infrastructure}

export template="${1:?Template not given}"

if [[ $template_default_zone_source_git == *"//"* ]]; then
  git_repository="${template_default_zone_source_git%//*}"
  directory="${template_default_zone_source_git#*//}"
  template_path=$directory/$template
else
  git_repository=$template_default_zone_source_git
  template_path=$template
fi

read -r -t 1 -n 1000 || : # Flush input buffer
echo
echo "HINT: Some namespaces are global in cloud environments. Therefore it is best"
echo "to use globally unique names to avoid naming conflicts."
echo
echo "Zone name? (e.g. 'myorg-$template', preferably globally unique)"
read -r zone

taito::execute_on_host_fg "
  export GIT_PAGER=''
  mkdir -p \${HOME}/.taito/tmp
  rm -rf \${HOME}/.taito/tmp/${zone}
  echo Cloning from ${git_repository}
  git clone -q -b master --single-branch --depth 1 ${git_repository} \${HOME}/.taito/tmp/${zone}
  echo Copying template ${template_path}
  cp -r \${HOME}/.taito/tmp/$zone/$template_path \"$zone\"
  taito ${taito_options:-} -- sed -i s/taito_zone=my-zone/taito_zone=$zone/ $zone/taito-config.sh
  echo
  echo Created new directory: \"$zone\"
  echo
  echo \"1) Go to the new directory: cd $zone\"
  echo \"2) Edit taito-config.sh and change at least all settings marked with '# CHANGE'\"
  echo \"3) Browse through the '*.yaml' files and change some settings if you like\"
  echo \"4) Run 'taito upgrade' to make sure your Taito CLI installation is up-to-date and clean\"
  echo \"5) Authenticate with 'taito auth' and follow instructions\"
  echo \"6) Apply configuration with 'taito zone apply' and follow instructions\"
  echo
"

taito::call_next "${@}"
