#!/bin/bash
: "${taito_plugin_path:?}"
: "${taito_namespace:?}"
: "${taito_project:?}"

# Change namespace
"${taito_plugin_path}/util/use-context"

. "${taito_plugin_path}/util/determine-pod-container"

if [[ -z "${pod}" ]]; then
  echo
  echo "kubectl: Please give pod name as argument:"
  (${taito_setv:?}; kubectl get pods)
else
  # Kubernetes
  (${taito_setv:?}; kubectl exec -it "${pod}" -c "${container}" -- "${@}")
fi
