#!/bin/bash -e

if [[ ${database_type:-} == "mysql" ]] || [[ -z "${database_type}" ]]; then
  source="${taito_env:?}"
  dest="${taito_dest_env:?}"
  username="${1:-root}"

  echo "TODO implement"
  echo "${database_instance:?}"
  echo "${database_name:?}"
  echo "${database_host:?}"
  echo "${database_port:?}"

fi

taito::call_next "${@}"
