#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

if [[ "${database_type:-}" == "mysql" ]] || [[ -z "${database_type}" ]]; then
  mysql::connect "${1}"
fi

taito::call_next "${@}"
