#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

if [[ ${database_type:-} == "mysql" ]] || [[ -z "${database_type}" ]]; then
  dump_file="${1:?}"
  # TODO: tool_options
  # tool_options="${*}"
  # tool_options="${*##* -- }"

  echo "Dumping database ${database_name:?} to file ${dump_file}. Please wait."
  echo "You can ignore the 'Access denied' error message related to tablespaces."
  mysql::dump > "${dump_file}"
  echo "Done"
fi

taito::call_next "${@}"
