#!/bin/bash
: "${taito_plugin_path:?}"

if [[ "${database_type:-}" == "mysql" ]] || [[ -z "${database_type}" ]]; then
  echo "Importing ${1}"
  "${taito_plugin_path}/util/mysql" < "${1}"
fi && \

taito::call_next "${@}"
