#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

# TODO: duplicate code with env-apply

if [[ "${taito_env}" == "local" ]]; then
  echo "Skipping database recreate for local environment"
else
  echo "Creating database(s)"
  (
    all=$(taito::print_targets_of_type database)
    databases=("${taito_target:-$all}")
    for database in ${databases[@]}; do
      export taito_target="${database}"
      taito::export_database_config "${database}"

      if [[ "${database_type:-}" == "mysql" ]] || [[ -z "${database_type}" ]]; then
        if taito::confirm "Create mysql database ${database_name}"; then
          # Create a subshell to contain password
          (
            export database_username=${database_master_username:-root}
            echo "HINT: You can get the ${database_username} user password from:"
            echo "${database_master_password_hint:-}"
            mysql::ask_and_expose_password
            mysql::create_users
            mysql::create_database
            echo "Created database ${database_name:-}"
          )
        fi
      fi
    done
  )
fi

taito::call_next "${@}"
