#!/bin/bash -e

if [[ "${taito_command}" == "db-"* ]]; then
  echo
  echo -e "${taito_command_context_prefix:-}${H1s}db-proxy${H1e}"
  echo "Stopping db proxy for ${database_name}"
  echo
fi

# Call next command on command chain
taito::call_next "${@}"
