#!/bin/bash -e

if [[ "${taito_command}" == "db-"* ]]; then
  taito::print_plugin_title
  echo "Starting db proxy for ${database_name}"
fi

# Call next command on command chain
taito::call_next "${@}"
