#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"
: "${taito_target:?}"
: "${taito_project:?}"
: "${taito_zone:?}"

taito::skip_if_not "function static" "${@}"
aws::publish_current_target_assets "${1}"

taito::call_next "${@}"
