#!/bin/bash -e
# shellcheck source=../../do/lib/all.bash
. "${taito_cli_path:?}/plugins/do/lib/all.bash"

if [[ ${taito_command:?} == "zone-"* ]]; then
  taito::print_plugin_title
  do::authenticate
fi

taito::call_next "${@}"
