#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"

# Modules with project prefix
terraform::run_all_by_prefix project apply "${taito_env:?}"

taito::call_next "${@}"
