#!/bin/bash -e
# shellcheck source=lib/all.bash
. "${taito_plugin_path:?}/lib/all.bash"
: "${taito_provider:?}"

(
  terraform::export_env
  cd "./scripts/terraform/${taito_provider}"
  terraform "${@}"
)

taito::call_next "${@}"
