#!/bin/bash
: "${taito_util_path:?}"
: "${database_name:?}"

echo "Database connection details:"
"${taito_util_path}/display-db-proxy-details"
echo

echo "TODO implement"

# Call next command on command chain
"${taito_util_path}/call-next" "${@}"
