#!/bin/bash -e
# shellcheck source=../links-global/lib/all.bash
. "${taito_cli_path:?}/plugins/links-global/lib/all.bash"

filter=${1}

echo

# Hack: Show dynamic links of link plugin in the correct place
links=$(links-global::show_help | sed ':a $!{N; ba}; s/\n/\\n/g')

if [[ -z "${filter}" ]]; then
  taito::show_file help.txt | \
    sed -e "s|PROJECT: DATABASE OPERATIONS|${links}\nPROJECT: DATABASE OPERATIONS|"
else
  echo QUICK EXAMPLES
  echo
  awk '/^QUICK EXAMPLES/,/^OPTIONS/' "${taito_cli_path}/help.txt" | \
    grep "^    ${filter//-/ }" | sed "s/^    /  /g"
  echo
  echo COMMANDS
  echo
  taito::show_file help.txt | \
    sed -e "s|PROJECT: DATABASE OPERATIONS|${links}\nPROJECT: DATABASE OPERATIONS|" | \
    awk "/^  [a-z]+/ && /${filter//-/ }/,/^$/"
fi

taito::call_next "${@}"
