#!/bin/bash -e
: "${taito_branch:?}"
: "${taito_vc_repository_url:?}"
: "${taito_target_env:?}"

taito::confirm "Do you want to execute CI/CD for ${taito_target_env}" || \
  taito::skip_to_next "${@}"

image_tag=$1
if [[ ! ${image_tag} ]]; then
  image_tag=$(git rev-parse "${taito_branch:?}")
fi

taito::execute_on_host_fg "
  function cleanup {
    rm -rf tmp/ci/${taito_target_env} &> /dev/null || :
  }
  cleanup
  trap cleanup EXIT
  mkdir -p tmp/ci
  git clone --single-branch --branch ${taito_branch} git@${taito_vc_repository_url/\//:} tmp/ci/${taito_target_env}
  taito -r ${taito_options:-} ci run continue:${taito_target_env} ${image_tag}
"

taito::call_next "${@}"
