#!/bin/bash -e
: "${taito_target_env:?}"

image_tag=$1

function cleanup {
  rm -rf "tmp/ci/$taito_target_env" &> /dev/null || :
}

(
  trap cleanup EXIT
  # TODO: fetch secrets from host instead
  cp -r secrets "tmp/ci/$taito_target_env" &> /dev/null || :
  cd "tmp/ci/$taito_target_env"
  echo "Image tag: ${image_tag}"
  taito::execute_with_ssh_agent "./local-ci ${taito_target_env} ${image_tag}"
)

taito::call_next "${@}"
