#!/bin/bash -e
: "${taito_app_url:?}"
: "${taito_target_env:?}"

extra_sleep_secs=${ci_test_wait:-15}
echo
echo
taito::print_note_start
echo "NOTE: Your application is now starting up at ${taito_target_env}!"
echo "Waiting extra ${extra_sleep_secs}s to make sure container rotate."
echo "You can configure sleep seconds with the ci_test_wait environment variable."
taito::print_note_end
echo
echo
sleep "${extra_sleep_secs}"

taito::call_next "${@}"
