#!/bin/bash -e
: "${taito_env:?}"

if [[ ${taito_mode:-} != "ci" ]] || [[ ${ci_exec_test:-} == "true" ]]; then
  if [[ -f ./taitoflag_test_failed ]]; then
    echo "Tests failed"
    if [[ ${ci_exec_revert:-} == "true" ]]; then
      echo "Reverting deployment"
      (
        taito::executing_start
        taito ${taito_options:-} "db revert:${taito_env}"
        taito ${taito_options:-} "deployment revert:${taito_env}"
      )
    fi
    exit 1
  fi
fi

taito::call_next "${@}"
