#!/bin/bash -e
: "${taito_target_env:?}"
: "${taito_project_path:?}"

# REFACTOR: duplicate code with build-prepare-50

if [[ ${taito_vc_provider:-} != "github" ]]; then
  echo "Currently only GitHub is supported. Skipping semantic release."
  taito::skip_to_next
fi

if [[ ${taito_mode:-} == "ci" ]] && [[ ${ci_exec_release:-} != "true" ]]; then
  echo "ci_exec_release setting is disabled. Skipping semantic release."
  taito::skip_to_next
fi

if [[ $secret_value_github_buildbot_token == "secret_file:"* ]]; then
  secret_value_github_buildbot_token="$(cat ${secret_value_github_buildbot_token#secret_file:})"
fi

if [[ ${secret_value_github_buildbot_token} != "ci" ]]; then
  echo "WARN: GitHub token has not been set. Skipping semantic release."
  taito::skip_to_next
fi

# Determine npm command based on environment
command=release-post:${taito_target_env}

# Run the command only if it exists in package.json
commands=$(npm run | grep '^  [^ ]*$' | sed -e 's/ //g')
if [[ $(echo "${commands}" | grep "^${command}$") != "" ]]; then
  (
    echo "Finalizing release"
    cd "${taito_project_path}/release" || exit 1
    taito::executing_start
    NPM_TOKEN=none GH_TOKEN=${secret_value_github_buildbot_token} \
      npm run "${command}"
    rm -f .npmrc
  )
fi

taito::call_next "${@}"
