#!/bin/bash -e
: "${taito_target_env:?}"
: "${taito_project_path:?}"

# Execute semantic release only if ci_exec_release is enabled
[[ ${taito_mode:-} != "ci" ]] || [[ ${ci_exec_release:-} == "true" ]] || \
  taito::skip_to_next

if [[ $secret_value_github_buildbot_token == "secret_file:"* ]]; then
  secret_value_github_buildbot_token="$(cat ${secret_value_github_buildbot_token#secret_file:})"
fi

# Determine npm command based on environment
command=release-post:${taito_target_env}

# Run the command only if it exists in package.json
commands=$(npm run | grep '^  [^ ]*$' | sed -e 's/ //g')
if [[ $(echo "${commands}" | grep "^${command}$") != "" ]]; then
  (
    echo "Finalizing release"
    cd "${taito_project_path}/release" || exit 1
    taito::executing_start
    NPM_TOKEN=none GH_TOKEN=${secret_value_github_buildbot_token} \
      npm run "${command}"
    rm -f .npmrc
  )
fi

taito::call_next "${@}"
